"""KidCoder – 24 coding levels (tutorial/test pairs)."""

LEVELS = [
    # === PAIR 1: Forward movement ===
    {
        "id": 1,
        "title": "📖 Pierwsze kroki",
        "description": "NAUKA: Doprowadź bohatera do gwiazdki! Użyj bloku DO PRZODU.",
        "grid_width": 5, "grid_height": 5,
        "hero_start": [0, 2], "hero_dir": "right",
        "goal": [3, 2], "walls": [],
        "available_blocks": ["forward", "forward", "forward"],
        "hints": ["Przeciągnij bloki DO PRZODU do obszaru programu", "Potrzebujesz 3 bloków DO PRZODU"],
    },
    {
        "id": 2,
        "title": "🧪 Test: Do przodu!",
        "description": "TEST: Poprowadź robota do gwiazdki sam!",
        "grid_width": 6, "grid_height": 5,
        "hero_start": [0, 2], "hero_dir": "right",
        "goal": [5, 2], "walls": [],
        "available_blocks": ["forward", "forward", "forward", "forward", "forward"],
        "hints": ["Ile kroków do gwiazdki? Policz kratki!"],
    },
    # === PAIR 2: Turning ===
    {
        "id": 3,
        "title": "📖 Skręcanie",
        "description": "NAUKA: Naucz się skręcać w prawo i w lewo!",
        "grid_width": 5, "grid_height": 5,
        "hero_start": [0, 0], "hero_dir": "right",
        "goal": [2, 2],
        "walls": [[3, 0], [3, 1], [3, 2]],
        "available_blocks": ["forward", "forward", "turn_right", "forward", "forward"],
        "hints": ["Idź do przodu 2 razy, skręć w prawo, potem idź 2 razy w dół"],
    },
    {
        "id": 4,
        "title": "🧪 Test: Skręty",
        "description": "TEST: Użyj skrętów żeby dotrzeć do celu!",
        "grid_width": 5, "grid_height": 5,
        "hero_start": [0, 4], "hero_dir": "right",
        "goal": [4, 0],
        "walls": [[2, 1], [2, 2], [2, 3], [2, 4]],
        "available_blocks": [
            "forward", "forward", "forward", "forward", "forward",
            "forward", "forward", "forward", "turn_left", "turn_right",
        ],
        "hints": ["Musisz iść w prawo, potem skręcić w górę, potem znów w prawo"],
    },
    # === PAIR 3: Loops ===
    {
        "id": 5,
        "title": "📖 Pętle",
        "description": "NAUKA: Użyj POWTÓRZ żeby nie pisać tych samych bloków wiele razy!",
        "grid_width": 7, "grid_height": 5,
        "hero_start": [0, 2], "hero_dir": "right",
        "goal": [6, 2], "walls": [],
        "available_blocks": ["repeat_3", "forward", "forward"],
        "hints": ["Włóż DO PRZODU do bloku POWTÓRZ ×3", "POWTÓRZ ×3 z 2× DO PRZODU = 6 kroków!"],
    },
    {
        "id": 6,
        "title": "🧪 Test: Pętle",
        "description": "TEST: Użyj pętli ze skrętami żeby przejść zakręt!",
        "grid_width": 7, "grid_height": 7,
        "hero_start": [0, 0], "hero_dir": "right",
        "goal": [6, 6], "walls": [],
        "available_blocks": [
            "repeat_3", "repeat_3",
            "forward", "forward", "forward", "forward", "turn_right",
        ],
        "hints": [
            "Pierwsza pętla: POWTÓRZ ×3 { DO PRZODU, DO PRZODU } = 6 w prawo",
            "Potem SKRĘT W PRAWO i druga pętla w dół!",
        ],
    },
    # === PAIR 4: Collecting gems ===
    {
        "id": 7,
        "title": "📖 Klejnoty",
        "description": "NAUKA: Zbierz klejnoty po drodze do celu! Użyj ZBIERZ gdy stoisz na klejnocie.",
        "grid_width": 7, "grid_height": 5,
        "hero_start": [0, 2], "hero_dir": "right",
        "goal": [6, 2],
        "gems": [[2, 2], [4, 2]], "walls": [],
        "available_blocks": [
            "forward", "forward", "forward", "forward",
            "forward", "forward", "collect", "collect",
        ],
        "hints": [
            "Użyj ZBIERZ gdy stoisz na klejnocie",
            "DO PRZODU ×2, ZBIERZ, DO PRZODU ×2, ZBIERZ, DO PRZODU ×2",
        ],
    },
    {
        "id": 8,
        "title": "🧪 Test: Klejnoty + pętla",
        "description": "TEST: Użyj pętli żeby zebrać wszystkie klejnoty!",
        "grid_width": 7, "grid_height": 5,
        "hero_start": [0, 2], "hero_dir": "right",
        "goal": [6, 2],
        "gems": [[1, 2], [2, 2], [3, 2], [4, 2], [5, 2]],
        "walls": [],
        "available_blocks": ["repeat_5", "forward", "collect", "forward"],
        "hints": [
            "POWTÓRZ ×5 { DO PRZODU, ZBIERZ } zbiera 5 klejnotów!",
            "Na końcu dodaj DO PRZODU żeby dojść do celu",
        ],
    },
    # === PAIR 5: Real Labyrinth ===
    {
        "id": 9,
        "title": "📖 Labirynt",
        "description": "NAUKA: Przeprowadź bohatera przez labirynt! Ściany blokują drogę – trzeba je obchodzić.",
        "grid_width": 7, "grid_height": 7,
        "hero_start": [0, 0], "hero_dir": "right",
        "goal": [6, 6],
        "walls": [
            [2, 0], [2, 1], [2, 2],
            [4, 2], [4, 3], [4, 4], [4, 5],
            [2, 4], [2, 5], [2, 6],
        ],
        "available_blocks": [
            "forward", "forward", "forward", "forward", "forward",
            "forward", "forward", "forward", "forward", "forward",
            "forward", "forward", "forward", "forward", "forward",
            "forward", "forward", "forward",
            "turn_right", "turn_right", "turn_right", "turn_right",
            "turn_left", "turn_left", "turn_left", "turn_left",
        ],
        "hints": [
            "Ściany blokują drogę! Musisz je obchodzić",
            "Idź w prawo, potem w dół, potem omijaj ściany ścinając zakręty",
            "Trasa: prawo do (1,0), dół do (1,3), prawo do (3,3), dół do (3,6), prawo do (6,6)",
        ],
    },
    {
        "id": 10,
        "title": "🧪 Test: Labirynt",
        "description": "TEST: Rozwiąż labirynt samodzielnie! Zbierz klejnot po drodze.",
        "grid_width": 7, "grid_height": 7,
        "hero_start": [0, 0], "hero_dir": "right",
        "goal": [6, 6],
        "gems": [[3, 2]],
        "walls": [
            [1, 1], [2, 1], [3, 1],
            [5, 0], [5, 1], [5, 2], [5, 3],
            [1, 3], [2, 3], [3, 3],
            [3, 5], [4, 5], [5, 5],
        ],
        "available_blocks": [
            "forward", "forward", "forward", "forward", "forward",
            "forward", "forward", "forward", "forward", "forward",
            "forward", "forward", "forward", "forward", "forward",
            "forward", "forward", "forward", "forward", "forward",
            "turn_right", "turn_right", "turn_right", "turn_right",
            "turn_right", "turn_left", "turn_left", "turn_left",
            "turn_left", "turn_left", "collect",
        ],
        "hints": [
            "Trzeba obejść ściany i zebrać klejnot na (3,2)",
            "Trasa: prawo do (4,0), dół do (4,2), lewo do zbierz (3,2), dół omijając, prawo na dół do celu",
        ],
    },
    # === PAIR 6: Wall navigation ===
    {
        "id": 11,
        "title": "📖 Obejdź ściankę!",
        "description": "NAUKA: Ściana blokuje drogę! Obejdź ją – skręć, omiń i jedź dalej!",
        "grid_width": 3, "grid_height": 3,
        "hero_start": [0, 1], "hero_dir": "right",
        "goal": [2, 1],
        "walls": [[1, 1]],
        "available_blocks": [
            "forward", "forward", "forward",
            "forward", "forward",
            "turn_right", "turn_right",
            "turn_left",
        ],
        "hints": [
            "Ściana blokuje drogę! Obejdź ją górą!",
            "Skręć w lewo (góra), idź do przodu, skręć w prawo, idź 2× do przodu, skręć w prawo, idź do przodu",
            "Rozwiązanie: W LEWO → DO PRZODU → W PRAWO → DO PRZODU → DO PRZODU → W PRAWO → DO PRZODU",
        ],
    },
    {
        "id": 12,
        "title": "🧪 Test: Obejdź ścianki!",
        "description": "TEST: Omijaj ściany i dotrzyj do celu samodzielnie!",
        "grid_width": 4, "grid_height": 3,
        "hero_start": [0, 1], "hero_dir": "right",
        "goal": [3, 1],
        "walls": [[2, 1]],
        "available_blocks": [
            "forward", "forward", "forward", "forward",
            "forward", "forward",
            "turn_right", "turn_right",
            "turn_left", "turn_left",
        ],
        "hints": [
            "Ściana blokuje drogę! Obejdź ją górą lub dołem.",
            "Idź do przodu, skręć w górę, obejdź ścianę i wróć na ścieżkę",
        ],
    },
    # === PAIR 7: If wall_ahead ===
    {
        "id": 13,
        "title": "📖 Sprytny ruch",
        "description": "NAUKA: Blok SPRYTNY RUCH idzie do przodu gdy wolne, a skręca gdy ściana!",
        "grid_width": 5, "grid_height": 5,
        "hero_start": [0, 0], "hero_dir": "right",
        "goal": [4, 4],
        "walls": [],
        "available_blocks": ["repeat_5", "repeat_5", "if_wall", "if_wall"],
        "hints": [
            "Włóż SPRYTNY RUCH do bloku POWTÓRZ ×5",
            "Robot skręci na krawędzi planszy!",
            "Dwa bloki POWTÓRZ ×5 ze SPRYTNYM RUCHEM w środku",
        ],
    },
    {
        "id": 14,
        "title": "🧪 Test: Sprytny robot",
        "description": "TEST: Użyj sprytnego ruchu żeby omijać ściany automatycznie!",
        "grid_width": 7, "grid_height": 5,
        "hero_start": [0, 0], "hero_dir": "right",
        "goal": [5, 4],
        "walls": [[6, 0], [6, 1], [6, 2], [6, 3]],
        "available_blocks": ["repeat_5", "repeat_5", "if_wall", "if_wall"],
        "hints": [
            "Robot napotka ścianę i skręci w dół!",
            "POWTÓRZ ×5 { SPRYTNY RUCH } + POWTÓRZ ×5 { SPRYTNY RUCH }",
        ],
    },
    # === PAIR 8: Functions ===
    {
        "id": 15,
        "title": "📖 Funkcje",
        "description": "NAUKA: Stwórz funkcję! Zdefiniuj raz, wywołaj wiele razy.",
        "grid_width": 5, "grid_height": 5,
        "hero_start": [0, 0], "hero_dir": "right",
        "goal": [4, 4],
        "walls": [],
        "available_blocks": [
            "define_func", "call_func", "call_func",
            "forward", "forward", "forward", "forward", "turn_right",
        ],
        "hints": [
            "Zdefiniuj funkcję: DO PRZODU ×4 + SKRĘT W PRAWO",
            "Potem wywołaj ją 2 razy!",
        ],
    },
    {
        "id": 16,
        "title": "🧪 Test: Funkcje",
        "description": "TEST: Użyj funkcji żeby rozwiązać problem efektywnie!",
        "grid_width": 5, "grid_height": 5,
        "hero_start": [0, 0], "hero_dir": "right",
        "goal": [2, 2],
        "walls": [],
        "available_blocks": [
            "define_func", "call_func", "call_func",
            "forward", "forward", "turn_right",
        ],
        "hints": [
            "Funkcja: DO PRZODU, DO PRZODU, SKRĘT W PRAWO",
            "Wywołaj 2 razy: prawo do (2,0) → dół do (2,2)!",
        ],
    },
    # === PAIR 9: Labirynt + klejnoty + ściany ===
    {
        "id": 17,
        "title": "📖 Labirynt z klejnotami",
        "description": "NAUKA: Omijaj ściany i zbieraj klejnoty po drodze!",
        "grid_width": 7, "grid_height": 5,
        "hero_start": [0, 2], "hero_dir": "right",
        "goal": [6, 2],
        "gems": [[1, 2], [5, 2]],
        "walls": [[3, 2]],
        "available_blocks": [
            "forward", "forward", "forward", "forward", "forward",
            "forward", "forward", "forward", "forward", "forward",
            "turn_right", "turn_right", "turn_left", "turn_left",
            "collect", "collect",
        ],
        "hints": [
            "Zbierz klejnot, potem obejdź ścianę górą!",
            "DO PRZODU, ZBIERZ, W LEWO, DO PRZODU, W PRAWO, DO PRZODU ×2, W PRAWO, DO PRZODU, W LEWO, ZBIERZ, DO PRZODU do celu",
        ],
    },
    {
        "id": 18,
        "title": "🧪 Test: Złożony labirynt",
        "description": "TEST: Rozwiąż złożony labirynt z klejnotami!",
        "grid_width": 7, "grid_height": 7,
        "hero_start": [0, 0], "hero_dir": "right",
        "goal": [6, 6],
        "gems": [[3, 0], [6, 3]],
        "walls": [
            [4, 0], [4, 1], [4, 2],
            [2, 2], [2, 3], [2, 4],
            [4, 4], [4, 5], [4, 6],
        ],
        "available_blocks": [
            "forward", "forward", "forward", "forward", "forward",
            "forward", "forward", "forward", "forward", "forward",
            "forward", "forward", "forward", "forward",
            "turn_right", "turn_right", "turn_right", "turn_right",
            "turn_left", "turn_left", "turn_left", "turn_left",
            "collect", "collect",
        ],
        "hints": [
            "Zbierz klejnot na (3,0), obejdź ściany, zbierz drugi na (6,3), potem do celu",
        ],
    },
    # === PAIR 10: Functions + loops ===
    {
        "id": 19,
        "title": "📖 Funkcje i pętle",
        "description": "NAUKA: Połącz pętle z funkcjami żeby pisać krótsze programy!",
        "grid_width": 7, "grid_height": 7,
        "hero_start": [0, 0], "hero_dir": "right",
        "goal": [6, 6],
        "walls": [],
        "available_blocks": [
            "define_func", "call_func", "call_func",
            "repeat_3", "forward", "forward", "turn_right",
        ],
        "hints": [
            "Zdefiniuj funkcję: POWTÓRZ ×3 { DO PRZODU, DO PRZODU } + SKRĘT W PRAWO",
            "Wywołaj ją dwukrotnie!",
        ],
    },
    {
        "id": 20,
        "title": "🧪 Test: Wszystko razem!",
        "description": "TEST: Użyj funkcji, pętli i zbierania!",
        "grid_width": 7, "grid_height": 7,
        "hero_start": [0, 0], "hero_dir": "right",
        "goal": [6, 6],
        "gems": [[6, 0]],
        "walls": [],
        "available_blocks": [
            "define_func", "call_func", "call_func",
            "forward", "forward", "forward",
            "forward", "forward", "forward",
            "turn_right", "collect",
        ],
        "hints": [
            "Funkcja: 6× DO PRZODU. Wywołaj → zbierz klejnot → skręt → wywołaj znów!",
        ],
    },
    # === PAIR 11: Warunki w pętlach ===
    {
        "id": 21,
        "title": "📖 Warunki w pętlach",
        "description": "NAUKA: Połącz POWTÓRZ z JEŚLI żeby robot sam decydował co robić!",
        "grid_width": 7, "grid_height": 5,
        "hero_start": [0, 0], "hero_dir": "right",
        "goal": [6, 4],
        "walls": [[6, 0], [6, 1], [6, 2], [6, 3]],
        "available_blocks": [
            "repeat_5", "repeat_5",
            "if_path_clear", "forward",
            "if_wall_ahead", "turn_right",
        ],
        "hints": [
            "W pętli: JEŚLI DROGA WOLNA → DO PRZODU, JEŚLI ŚCIANA → SKRĘT W PRAWO",
            "Robot sam objedzie ścianę i dojdzie do celu!",
        ],
    },
    {
        "id": 22,
        "title": "🧪 Test: Inteligentny robot",
        "description": "TEST: Zaprogramuj robota żeby sam przeszedł przez przeszkody!",
        "grid_width": 7, "grid_height": 7,
        "hero_start": [0, 0], "hero_dir": "right",
        "goal": [6, 6],
        "walls": [
            [6, 0], [6, 1], [6, 2],
            [0, 4], [1, 4], [2, 4], [3, 4], [4, 4],
        ],
        "available_blocks": [
            "repeat_5", "repeat_5", "repeat_5",
            "if_path_clear", "if_path_clear",
            "forward", "forward",
            "if_wall_ahead", "if_wall_ahead",
            "turn_right", "turn_left",
        ],
        "hints": [
            "Robot musi przejść w prawo, skręcić w dół, potem znów w prawo",
            "Użyj wielu powtórzeń z warunkami!",
        ],
    },
    # === PAIR 12: Master challenge ===
    {
        "id": 23,
        "title": "📖 Wielki labirynt",
        "description": "NAUKA: Najtrudniejszy labirynt! Użyj wszystkich umiejętności!",
        "grid_width": 9, "grid_height": 9,
        "hero_start": [0, 0], "hero_dir": "right",
        "goal": [8, 8],
        "gems": [[4, 0], [8, 4]],
        "walls": [
            [2, 0], [2, 1],
            [4, 2], [4, 3], [4, 4],
            [2, 4], [2, 5], [2, 6],
            [6, 4], [6, 5], [6, 6], [6, 7],
            [4, 7], [4, 8],
        ],
        "available_blocks": [
            "forward", "forward", "forward", "forward", "forward",
            "forward", "forward", "forward", "forward", "forward",
            "forward", "forward", "forward", "forward", "forward",
            "forward", "forward", "forward", "forward", "forward",
            "forward", "forward", "forward", "forward",
            "turn_right", "turn_right", "turn_right", "turn_right",
            "turn_right", "turn_right",
            "turn_left", "turn_left", "turn_left", "turn_left",
            "turn_left", "turn_left",
            "collect", "collect",
        ],
        "hints": [
            "Zbierz oba klejnoty i dotrzeć do (8,8)",
            "Jedna z dróg: prawo, klejnot(4,0), dół, omijaj ściany, klejnot(8,4), dół do celu",
        ],
    },
    {
        "id": 24,
        "title": "🧪 Mistrz programista!",
        "description": "TEST KOŃCOWY: Pokaż wszystko czego się nauczyłeś!",
        "grid_width": 9, "grid_height": 9,
        "hero_start": [0, 0], "hero_dir": "right",
        "goal": [8, 8],
        "gems": [[4, 0], [0, 4], [8, 4]],
        "walls": [
            [2, 1], [3, 1], [4, 1],
            [6, 0], [6, 1], [6, 2], [6, 3],
            [1, 3], [2, 3],
            [4, 3], [4, 4], [4, 5],
            [2, 5], [2, 6], [2, 7],
            [6, 6], [6, 7], [6, 8],
        ],
        "available_blocks": [
            "define_func", "call_func",
            "repeat_3", "repeat_5",
            "if_path_clear", "forward",
            "if_wall_ahead", "turn_right",
            "forward", "forward", "forward", "forward", "forward",
            "forward", "forward", "forward", "forward", "forward",
            "forward", "forward", "forward", "forward", "forward",
            "forward", "forward", "forward", "forward",
            "turn_right", "turn_right", "turn_right",
            "turn_left", "turn_left", "turn_left", "turn_left",
            "collect", "collect", "collect",
        ],
        "hints": [
            "Wykorzystaj funkcje, pętle i warunki!",
            "Zbierz 3 klejnoty i dotrzeć do celu w (8,8)",
        ],
    },
]
