"""KidCoder – 22 logic puzzles (tutorial/test pairs)."""

LOGIC_PUZZLES = [
    {
        "id": 1,
        "title": "📖 Kontynuuj ciąg",
        "description": "NAUKA: Znajdź wzorzec w ciągu liczb i uzupełnij brakującą!",
        "type": "sequence",
        "sequence": [2, 4, 6, 8, None],
        "answer": 10,
        "options": [9, 10, 11, 12],
        "explanation": "Każda kolejna liczba jest o 2 większa: 2+2=4, 4+2=6, 6+2=8, 8+2=10",
        "hints": ["Popatrz na różnicę między liczbami", "Każdy krok to +2"],
    },
    {
        "id": 2,
        "title": "🧪 Test: Ciąg liczb",
        "description": "TEST: Jaka jest następna liczba?",
        "type": "sequence",
        "sequence": [1, 3, 5, 7, None],
        "answer": 9,
        "options": [8, 9, 10, 11],
        "explanation": "Liczby nieparzyste: 1, 3, 5, 7, 9 (każda +2)",
        "hints": ["To ciąg liczb nieparzystych"],
    },
    {
        "id": 3,
        "title": "📖 Wzorzec kolorów",
        "description": "NAUKA: Jaki kolor powinien być następny?",
        "type": "pattern",
        "pattern": ["🔴", "🔵", "🔴", "🔵", "🔴", None],
        "answer": "🔵",
        "options": ["🔴", "🔵", "🟢", "🟡"],
        "explanation": "Kolory się powtarzają: czerwony, niebieski, czerwony, niebieski... Następny jest niebieski!",
        "hints": ["Popatrz na powtarzający się wzorzec"],
    },
    {
        "id": 4,
        "title": "🧪 Test: Wzorzec",
        "description": "TEST: Jaki element powinien być następny?",
        "type": "pattern",
        "pattern": ["🌟", "🌙", "🌟", "🌙", "🌟", None],
        "answer": "🌙",
        "options": ["🌟", "🌙", "☀️", "⚡"],
        "explanation": "Gwiazdka i księżyc na zmianę. Następny: 🌙",
        "hints": ["Dwa elementy powtarzają się na zmianę"],
    },
    {
        "id": 5,
        "title": "📖 Logiczne JEŚLI-TO",
        "description": "NAUKA: Jeśli pada deszcz, biorę parasol. Pada deszcz. Co robię?",
        "type": "logic_if",
        "condition": "Pada deszcz ☔",
        "rule": "Jeśli pada deszcz → biorę parasol 🌂",
        "answer": "Biorę parasol 🌂",
        "options": ["Biorę parasol 🌂", "Biorę okulary 🕶️", "Nic nie robię", "Idę w kalosze 🥾"],
        "explanation": "Zasada mówi: jeśli pada deszcz → parasol. Pada deszcz, więc biorę parasol!",
        "hints": ["Przeczytaj zasadę JEŚLI-TO i sprawdź czy warunek jest spełniony"],
    },
    {
        "id": 6,
        "title": "🧪 Test: JEŚLI-TO",
        "description": "TEST: Jeśli jest ciemno, włączam lampę. Jest ciemno. Co robię?",
        "type": "logic_if",
        "condition": "Jest ciemno 🌑",
        "rule": "Jeśli jest ciemno → włączam lampę 💡",
        "answer": "Włączam lampę 💡",
        "options": ["Włączam lampę 💡", "Otwieram okno 🪟", "Idę spać 😴", "Jem obiad 🍽️"],
        "explanation": "Zasada: ciemno → lampa. Jest ciemno, więc włączam lampę!",
        "hints": ["Warunek jest spełniony – co mówi zasada?"],
    },
    {
        "id": 7,
        "title": "📖 Złożony wzorzec",
        "description": "NAUKA: Znajdź wzorzec z 3 elementami!",
        "type": "pattern",
        "pattern": ["🍎", "🍌", "🍊", "🍎", "🍌", None],
        "answer": "🍊",
        "options": ["🍎", "🍌", "🍊", "🍇"],
        "explanation": "Wzorzec: jabłko, banan, pomarańcza – powtarza się! Następna: 🍊",
        "hints": ["To wzorzec z trzema elementami", "🍎🍌🍊 powtarza się cyklicznie"],
    },
    {
        "id": 8,
        "title": "🧪 Test: Złożony wzorzec",
        "description": "TEST: Co następne?",
        "type": "pattern",
        "pattern": ["⬛", "⬜", "⬛", "⬛", "⬜", None],
        "answer": "⬛",
        "options": ["⬛", "⬜", "🟥", "🟦"],
        "explanation": "Wzorzec: czarny, biały, czarny, czarny, biały, czarny – powtarza się po 3!",
        "hints": ["Popatrz na grupy po 3 elementy"],
    },
    {
        "id": 9,
        "title": "📖 Ciąg rosnący",
        "description": "NAUKA: Każda liczba rośnie coraz szybciej!",
        "type": "sequence",
        "sequence": [1, 2, 4, 8, None],
        "answer": 16,
        "options": [10, 12, 14, 16],
        "explanation": "Każda liczba jest 2 razy większa: 1×2=2, 2×2=4, 4×2=8, 8×2=16",
        "hints": ["Każda liczba jest podwojona", "Mnożenie przez 2!"],
    },
    {
        "id": 10,
        "title": "🧪 Test: Ciąg trudny",
        "description": "TEST: Jaka jest następna liczba?",
        "type": "sequence",
        "sequence": [1, 4, 9, 16, None],
        "answer": 25,
        "options": [20, 22, 25, 30],
        "explanation": "To kwadraty! 1²=1, 2²=4, 3²=9, 4²=16, 5²=25",
        "hints": ["Pomyśl o mnożeniu liczby przez siebie", "1×1, 2×2, 3×3..."],
    },
    {
        "id": 11,
        "title": "📖 PRAWDA czy FAŁSZ",
        "description": "NAUKA: Oceń czy zdanie jest prawdziwe!",
        "type": "true_false",
        "statement": "Wszystkie koty mają cztery łapy. Mruczek jest kotem. Czy Mruczek ma cztery łapy?",
        "answer": "Prawda ✅",
        "options": ["Prawda ✅", "Fałsz ❌"],
        "explanation": "WSZYSTKIE koty mają 4 łapy + Mruczek jest kotem = Mruczek ma 4 łapy. PRAWDA!",
        "hints": ["Przeczytaj oba zdania i połącz je logicznie"],
    },
    {
        "id": 12,
        "title": "🧪 Test: PRAWDA czy FAŁSZ",
        "description": "TEST: Oceń zdanie!",
        "type": "true_false",
        "statement": "Wszystkie ryby żyją w wodzie. Karp jest rybą. Czy karp żyje w wodzie?",
        "answer": "Prawda ✅",
        "options": ["Prawda ✅", "Fałsz ❌"],
        "explanation": "WSZYSTKIE ryby żyją w wodzie + karp jest rybą = karp żyje w wodzie. PRAWDA!",
        "hints": ["Przeczytaj oba zdania i połącz je logicznie", "Karp jest rybą, a ryby żyją w wodzie..."],
    },
    {
        "id": 13,
        "title": "📖 I, LUB",
        "description": "NAUKA: Aby dostać ciastko: musisz posprzątać I zjeść obiad. Posprzątałeś i zjadłeś obiad. Ciastko?",
        "type": "logic_gate",
        "inputs": [True, True],
        "gate": "AND",
        "rule": "Posprzątałeś ✅ I Zjadłeś obiad ✅ → Ciastko?",
        "answer": "TAK! 🍪",
        "options": ["TAK! 🍪", "NIE ❌"],
        "explanation": "Oba warunki spełnione (I = oba muszą być PRAWDA) → TAK, ciastko!",
        "hints": ["I (AND) = oba warunki muszą być spełnione"],
    },
    {
        "id": 14,
        "title": "🧪 Test: I, LUB",
        "description": "TEST: Aby wyjść na dwór: pogoda musi być ładna LUB musisz mieć parasol. Brzydka pogoda, ale masz parasol. Wychodzisz?",
        "type": "logic_gate",
        "inputs": [False, True],
        "gate": "OR",
        "rule": "Ładna pogoda ❌ LUB Masz parasol ✅ → Wychodzisz?",
        "answer": "TAK! 🚶",
        "options": ["TAK! 🚶", "NIE ❌"],
        "explanation": "LUB (OR) = wystarczy JEDEN warunek. Masz parasol → TAK, wychodzisz!",
        "hints": ["LUB (OR) = wystarczy że jedno jest prawdą"],
    },
    {
        "id": 15,
        "title": "📖 Sortowanie",
        "description": "NAUKA: Ułóż liczby od najmniejszej do największej!",
        "type": "sort",
        "items": [5, 1, 8, 3],
        "answer": [1, 3, 5, 8],
        "options": [[1, 3, 5, 8], [8, 5, 3, 1], [1, 5, 3, 8], [3, 1, 8, 5]],
        "explanation": "Od najmniejszej: 1, 3, 5, 8",
        "hints": ["Znajdź najmniejszą, potem następną..."],
    },
    {
        "id": 16,
        "title": "🧪 Test: Sortowanie",
        "description": "TEST: Ułóż od najmniejszej!",
        "type": "sort",
        "items": [9, 2, 7, 4, 1],
        "answer": [1, 2, 4, 7, 9],
        "options": [[1, 2, 4, 7, 9], [9, 7, 4, 2, 1], [1, 4, 2, 7, 9], [2, 1, 4, 9, 7]],
        "explanation": "Od najmniejszej: 1, 2, 4, 7, 9",
        "hints": ["Szukaj zawsze najmniejszej z pozostałych"],
    },
    # === PAIR 9: Find the path ===
    {
        "id": 17,
        "title": "📖 Znajdź drogę",
        "description": "NAUKA: Który kierunek prowadzi robota do gwiazdki?",
        "type": "find_path",
        "grid": [
            ["🤖", "➡️", "➡️", "⬇️"],
            ["⬛", "⬛", "⬛", "⬇️"],
            ["⬛", "⬛", "⬛", "⭐"],
        ],
        "question": "Robot jest w lewym górnym rogu. Jak dojść do ⭐?",
        "answer": "➡️ ➡️ ⬇️ ⬇️",
        "options": ["➡️ ➡️ ⬇️ ⬇️", "⬇️ ⬇️ ➡️ ➡️", "➡️ ⬇️ ➡️ ⬇️", "⬇️ ➡️ ⬇️ ➡️"],
        "explanation": "Robot idzie: prawo, prawo (do końca rzędu), potem dół, dół do gwiazdki!",
        "hints": ["Robot musi dotrzeć do prawego dolnego rogu", "Najpierw idź w prawo, potem w dół"],
    },
    {
        "id": 18,
        "title": "🧪 Test: Znajdź drogę",
        "description": "TEST: Poprowadź robota do celu!",
        "type": "find_path",
        "grid": [
            ["🤖", "⬛", "⬛"],
            ["⬇️", "⬛", "⬛"],
            ["➡️", "➡️", "⭐"],
        ],
        "question": "Jak robot dotrze do ⭐?",
        "answer": "⬇️ ⬇️ ➡️ ➡️",
        "options": ["⬇️ ⬇️ ➡️ ➡️", "➡️ ➡️ ⬇️ ⬇️", "⬇️ ➡️ ⬇️ ➡️", "➡️ ⬇️ ➡️ ⬇️"],
        "explanation": "Robot idzie: dół, dół, potem prawo, prawo do gwiazdki!",
        "hints": ["Robot musi najpierw zejść na dół"],
    },
    # === PAIR 10: Mirror pattern ===
    {
        "id": 19,
        "title": "📖 Lustrzane odbicie",
        "description": "NAUKA: Znajdź lustrzane odbicie wzoru!",
        "type": "mirror",
        "pattern": ["🟥", "🟦", "🟨"],
        "question": "Jaki jest lustrzany (odwrócony) wzór?",
        "answer": "🟨 🟦 🟥",
        "options": ["🟨 🟦 🟥", "🟥 🟨 🟦", "🟦 🟥 🟨", "🟥 🟦 🟨"],
        "explanation": "Lustrzane odbicie = odwracamy kolejność! 🟥🟦🟨 → 🟨🟦🟥",
        "hints": ["Lustro odwraca kolejność elementów", "Przeczytaj wzór od końca"],
    },
    {
        "id": 20,
        "title": "🧪 Test: Lustrzane odbicie",
        "description": "TEST: Odwróć wzór!",
        "type": "mirror",
        "pattern": ["⬆️", "➡️", "⬇️", "⬅️"],
        "question": "Jaki jest lustrzany (odwrócony) wzór?",
        "answer": "⬅️ ⬇️ ➡️ ⬆️",
        "options": ["⬅️ ⬇️ ➡️ ⬆️", "⬆️ ⬅️ ⬇️ ➡️", "➡️ ⬆️ ⬅️ ⬇️", "⬇️ ➡️ ⬆️ ⬅️"],
        "explanation": "Lustrzane odbicie: ⬆️➡️⬇️⬅️ → ⬅️⬇️➡️⬆️",
        "hints": ["Odwróć kolejność strzałek"],
    },
    # === PAIR 11: Harder sequence ===
    {
        "id": 21,
        "title": "📖 Ciąg Fibonacciego",
        "description": "NAUKA: Każda liczba to suma dwóch poprzednich!",
        "type": "sequence",
        "sequence": [1, 1, 2, 3, 5, None],
        "answer": 8,
        "options": [6, 7, 8, 10],
        "explanation": "Ciąg Fibonacciego: 3+5=8. Każda liczba = suma dwóch poprzednich!",
        "hints": ["Dodaj dwie ostatnie liczby", "3 + 5 = ?"],
    },
    {
        "id": 22,
        "title": "🧪 Test: Ciąg Fibonacciego",
        "description": "TEST: Co dalej w ciągu?",
        "type": "sequence",
        "sequence": [2, 3, 5, 8, None],
        "answer": 13,
        "options": [10, 11, 13, 15],
        "explanation": "5+8=13. To dalej ciąg Fibonacciego!",
        "hints": ["Dodaj dwie ostatnie liczby"],
    },
    # === PAIR 12: Complex IF-ELSE ===
    {
        "id": 23,
        "title": "📖 JEŚLI-INACZEJ",
        "description": "NAUKA: Co się stanie gdy warunek NIE jest spełniony?",
        "type": "logic_if",
        "condition": "Jest słonecznie ☀️",
        "rule": "Jeśli pada deszcz → biorę parasol 🌂, INACZEJ → biorę okulary 🕶️",
        "answer": "Biorę okulary 🕶️",
        "options": ["Biorę parasol 🌂", "Biorę okulary 🕶️", "Nic nie robię", "Zostaję w domu 🏠"],
        "explanation": "Nie pada deszcz (jest słonecznie), więc idziemy do INACZEJ → okulary!",
        "hints": ["Warunek (pada deszcz) NIE jest spełniony", "Co mówi INACZEJ?"],
    },
    {
        "id": 24,
        "title": "🧪 Test: JEŚLI-INACZEJ",
        "description": "TEST: Jeśli temp > 25°C → włączam wentylator, INACZEJ → zakładam bluzę. Temp = 18°C.",
        "type": "logic_if",
        "condition": "Temperatura = 18°C 🌡️",
        "rule": "Jeśli temp > 25°C → wentylator 🌀, INACZEJ → bluza 🧥",
        "answer": "Zakładam bluzę 🧥",
        "options": ["Włączam wentylator 🌀", "Zakładam bluzę 🧥", "Otwieram okno 🪟", "Jem lody 🍦"],
        "explanation": "18°C < 25°C, więc warunek nie spełniony → INACZEJ → bluza!",
        "hints": ["Czy 18 jest większe od 25?"],
    },
    # === PAIR 13: NOT logic ===
    {
        "id": 25,
        "title": "📖 Negacja (NIE)",
        "description": "NAUKA: NIE zmienia PRAWDĘ na FAŁSZ i odwrotnie!",
        "type": "logic_gate",
        "inputs": [True],
        "gate": "NOT",
        "rule": "Zdanie: Pada deszcz ✅ → NIE pada deszcz = ?",
        "answer": "FAŁSZ ❌",
        "options": ["PRAWDA ✅", "FAŁSZ ❌"],
        "explanation": "NIE (NOT) odwraca wartość: PRAWDA → FAŁSZ!",
        "hints": ["NIE zamienia prawdę na fałsz"],
    },
    {
        "id": 26,
        "title": "🧪 Test: Negacja",
        "description": "TEST: Ala NIE ma kota. Ala ma kota = FAŁSZ. Co daje NIE FAŁSZ?",
        "type": "logic_gate",
        "inputs": [False],
        "gate": "NOT",
        "rule": "Ala ma kota = FAŁSZ ❌ → NIE(Ala ma kota) = ?",
        "answer": "PRAWDA ✅",
        "options": ["PRAWDA ✅", "FAŁSZ ❌"],
        "explanation": "NIE FAŁSZ = PRAWDA! Ala nie ma kota, więc 'Ala NIE ma kota' to prawda!",
        "hints": ["NIE zamienia FAŁSZ na PRAWDĘ"],
    },
    # === PAIR 14: Complex pattern ===
    {
        "id": 27,
        "title": "📖 Wzorzec rosnący",
        "description": "NAUKA: Elementy powtarzają się, ale ich ilość rośnie!",
        "type": "pattern",
        "pattern": ["⭐", "⭐⭐", "⭐⭐⭐", None],
        "answer": "⭐⭐⭐⭐",
        "options": ["⭐⭐⭐⭐", "⭐⭐⭐", "⭐⭐", "⭐⭐⭐⭐⭐"],
        "explanation": "Jedna gwiazdka więcej za każdym razem: 1, 2, 3, 4!",
        "hints": ["Ile gwiazdek w każdym elemencie?", "1, 2, 3, ...?"],
    },
    {
        "id": 28,
        "title": "🧪 Test: Wzorzec rosnący",
        "description": "TEST: Co dalej?",
        "type": "pattern",
        "pattern": ["🔵", "🔵🔴", "🔵🔴🟢", None],
        "answer": "🔵🔴🟢🟡",
        "options": ["🔵🔴🟢🟡", "🔵🔴🟢🔵", "🟡🟢🔴🔵", "🔵🔵🔵🔵"],
        "explanation": "Każdy element dodaje nowy kolor: 1, 2, 3 → 4 kolory!",
        "hints": ["Każdy element ma o jeden kolor więcej"],
    },
    # === PAIR 15: Double condition ===
    {
        "id": 29,
        "title": "📖 Dwa warunki (I + LUB)",
        "description": "NAUKA: (Pada I jest zimno) LUB masz parasol → zostajesz w domu?",
        "type": "logic_gate",
        "inputs": [True, True, False],
        "gate": "COMPLEX",
        "rule": "Pada ✅ I Zimno ✅ → nieprzyjemnie ✅. Nieprzyjemnie ✅ LUB brak parasola ❌ = ?",
        "answer": "TAK, zostań w domu 🏠",
        "options": ["TAK, zostań w domu 🏠", "NIE, wyjdź na dwór 🚶"],
        "explanation": "Pada I zimno = nieprzyjemnie (PRAWDA). LUB: wystarczy jedno – zostajesz w domu!",
        "hints": ["Najpierw oceń I, potem LUB"],
    },
    {
        "id": 30,
        "title": "🧪 Test: Dwa warunki",
        "description": "TEST: (Masz bilet I paszport) LUB jesteś pilotem → lecisz?",
        "type": "logic_gate",
        "inputs": [True, False, False],
        "gate": "COMPLEX",
        "rule": "Bilet ✅ I Paszport ❌ → komplet? ❌. Komplet ❌ LUB Pilot ❌ = ?",
        "answer": "NIE lecisz ❌",
        "options": ["Lecisz ✈️", "NIE lecisz ❌"],
        "explanation": "Bilet I paszport: brak paszportu = FAŁSZ. Nie jesteś pilotem = FAŁSZ. FAŁSZ LUB FAŁSZ = FAŁSZ!",
        "hints": ["I wymaga obu warunków", "Nie masz paszportu ani nie jesteś pilotem"],
    },
    # === PAIR 16: Sort words ===
    {
        "id": 31,
        "title": "📖 Sortowanie alfabetyczne",
        "description": "NAUKA: Ułóż słowa w kolejności A-Z!",
        "type": "sort",
        "items": ["🍌 Banan", "🍎 Arbuz", "🍒 Czereśnia", "🥝 Kiwi"],
        "answer": ["🍎 Arbuz", "🍌 Banan", "🍒 Czereśnia", "🥝 Kiwi"],
        "options": [
            ["🍎 Arbuz", "🍌 Banan", "🍒 Czereśnia", "🥝 Kiwi"],
            ["🍌 Banan", "🍎 Arbuz", "🍒 Czereśnia", "🥝 Kiwi"],
            ["🍒 Czereśnia", "🍎 Arbuz", "🍌 Banan", "🥝 Kiwi"],
            ["🥝 Kiwi", "🍒 Czereśnia", "🍌 Banan", "🍎 Arbuz"],
        ],
        "explanation": "Alfabetycznie: Arbuz, Banan, Czereśnia, Kiwi!",
        "hints": ["A jest przed B, B przed C..."],
    },
    {
        "id": 32,
        "title": "🧪 Test: Sortowanie alfabetyczne",
        "description": "TEST: Ułóż od A do Z!",
        "type": "sort",
        "items": ["🐕 Pies", "🐈 Kot", "🐘 Słoń", "🐟 Ryba"],
        "answer": ["🐈 Kot", "🐕 Pies", "🐟 Ryba", "🐘 Słoń"],
        "options": [
            ["🐈 Kot", "🐕 Pies", "🐟 Ryba", "🐘 Słoń"],
            ["🐕 Pies", "🐈 Kot", "🐟 Ryba", "🐘 Słoń"],
            ["🐘 Słoń", "🐟 Ryba", "🐕 Pies", "🐈 Kot"],
            ["🐟 Ryba", "🐈 Kot", "🐘 Słoń", "🐕 Pies"],
        ],
        "explanation": "Alfabetycznie: Kot, Pies, Ryba, Słoń!",
        "hints": ["K jest przed P, P przed R, R przed S"],
    },
    # === PAIR 17: Tricky true/false ===
    {
        "id": 33,
        "title": "📖 Logiczny podchwytliwy",
        "description": "NAUKA: Niektóre jabłka są czerwone. To jabłko jest zielone. Czy jest jabłkiem?",
        "type": "true_false",
        "statement": "Niektóre jabłka są czerwone. To jabłko jest zielone. Czy to nadal jest jabłko?",
        "answer": "Prawda ✅",
        "options": ["Prawda ✅", "Fałsz ❌"],
        "explanation": "TAK! Jabłko może być zielone – powiedzieliśmy NIEKTÓRE są czerwone, nie WSZYSTKIE!",
        "hints": ["Czy 'niektóre' znaczy 'wszystkie'?"],
    },
    {
        "id": 34,
        "title": "🧪 Test: Logiczny podchwytliwy",
        "description": "TEST: Wszystkie psy szczekają. Reks nie szczeka. Czy Reks jest psem?",
        "type": "true_false",
        "statement": "Wszystkie psy szczekają. Reks nie szczeka. Czy Reks jest psem?",
        "answer": "Fałsz ❌",
        "options": ["Prawda ✅", "Fałsz ❌"],
        "explanation": "FAŁSZ! Skoro WSZYSTKIE psy szczekają, a Reks nie szczeka, to Reks nie jest psem!",
        "hints": ["WSZYSTKIE psy szczekają – bez wyjątku"],
    },
    # === PAIR 18: Harder find path ===
    {
        "id": 35,
        "title": "📖 Labirynt robota",
        "description": "NAUKA: Poprowadź robota przez labirynt!",
        "type": "find_path",
        "grid": [
            ["🤖", "⬛", "⬛", "⬛"],
            ["⬇️", "⬛", "⬛", "⬛"],
            ["➡️", "➡️", "⬛", "⬛"],
            ["⬛", "⬇️", "⬛", "⬛"],
            ["⬛", "➡️", "➡️", "⭐"],
        ],
        "question": "Jak robot dotrze do ⭐ omijając ściany?",
        "answer": "⬇️ ⬇️ ➡️ ⬇️ ⬇️ ➡️ ➡️",
        "options": ["⬇️ ⬇️ ➡️ ⬇️ ⬇️ ➡️ ➡️", "➡️ ➡️ ➡️ ⬇️ ⬇️ ⬇️ ⬇️", "⬇️ ⬇️ ⬇️ ⬇️ ➡️ ➡️ ➡️", "⬇️ ➡️ ⬇️ ➡️ ⬇️ ➡️ ⬇️"],
        "explanation": "Robot: dół ×2, prawo, dół ×2, prawo ×2 do gwiazdki!",
        "hints": ["Śledź ścieżkę na mapce", "Robot nie może iść przez ścianę ⬛"],
    },
    {
        "id": 36,
        "title": "🧪 Test: Labirynt robota",
        "description": "TEST: Znajdź drogę!",
        "type": "find_path",
        "grid": [
            ["🤖", "➡️", "⬇️", "⬛"],
            ["⬛", "⬛", "⬇️", "⬛"],
            ["⬛", "⬛", "➡️", "⭐"],
        ],
        "question": "Jak robot dotrze do ⭐?",
        "answer": "➡️ ➡️ ⬇️ ⬇️ ➡️",
        "options": ["➡️ ➡️ ⬇️ ⬇️ ➡️", "⬇️ ⬇️ ➡️ ➡️ ➡️", "➡️ ⬇️ ➡️ ⬇️ ➡️", "⬇️ ➡️ ➡️ ⬇️ ➡️"],
        "explanation": "Robot: prawo ×2, dół ×2, prawo do celu!",
        "hints": ["Idź w prawo, potem w dół, potem znów w prawo"],
    },
    # === PAIR 19: Sequence with subtraction ===
    {
        "id": 37,
        "title": "📖 Ciąg malejący",
        "description": "NAUKA: Każda liczba jest mniejsza od poprzedniej!",
        "type": "sequence",
        "sequence": [20, 17, 14, 11, None],
        "answer": 8,
        "options": [7, 8, 9, 10],
        "explanation": "Każda liczba jest o 3 mniejsza: 20-3=17, 17-3=14, 14-3=11, 11-3=8",
        "hints": ["O ile zmniejsza się każda liczba?", "Odejmij 3!"],
    },
    {
        "id": 38,
        "title": "🧪 Test: Ciąg malejący",
        "description": "TEST: Jaka jest następna liczba?",
        "type": "sequence",
        "sequence": [50, 45, 40, 35, None],
        "answer": 30,
        "options": [25, 28, 30, 32],
        "explanation": "Każda liczba jest o 5 mniejsza: 35-5=30",
        "hints": ["Ile odejmujemy za każdym razem?"],
    },
    # === PAIR 20: Complex pattern with rotation ===
    {
        "id": 39,
        "title": "📖 Wzorzec obrotowy",
        "description": "NAUKA: Strzałki się obracają!",
        "type": "pattern",
        "pattern": ["⬆️", "➡️", "⬇️", "⬅️", None],
        "answer": "⬆️",
        "options": ["⬆️", "➡️", "⬇️", "⬅️"],
        "explanation": "Strzałki obracają się zgodnie ze wskazówkami zegara i wracają do początku: ⬆️!",
        "hints": ["Strzałki idą w kółko", "Po ⬅️ znów ⬆️"],
    },
    {
        "id": 40,
        "title": "🧪 Test: Wzorzec obrotowy",
        "description": "TEST: Co następne?",
        "type": "pattern",
        "pattern": ["🌑", "🌒", "🌓", "🌔", "🌕", "🌖", "🌗", None],
        "answer": "🌘",
        "options": ["🌘", "🌑", "🌕", "🌒"],
        "explanation": "Fazy księżyca po kolei! Po 🌗 następuje 🌘",
        "hints": ["To cykl faz księżyca"],
    },
    # === PAIR 21: Complex true/false with multiple conditions ===
    {
        "id": 41,
        "title": "📖 Logiczny łańcuch",
        "description": "NAUKA: Połącz kilka informacji w łańcuch!",
        "type": "true_false",
        "statement": "Wszystkie ptaki mają skrzydła. Orzeł jest ptakiem. Orzeł lata. Czy WSZYSTKIE ptaki latają?",
        "answer": "Fałsz ❌",
        "options": ["Prawda ✅", "Fałsz ❌"],
        "explanation": "FAŁSZ! To że orzeł lata, nie znaczy że wszystkie ptaki latają (np. pingwin nie lata)!",
        "hints": ["Czy z jednego przykładu możesz wnioskować o wszystkich?"],
    },
    {
        "id": 42,
        "title": "🧪 Test: Logiczny łańcuch",
        "description": "TEST: Oceń zdanie logicznie!",
        "type": "true_false",
        "statement": "Jeśli pada deszcz → ulica jest mokra. Ulica jest mokra. Czy na pewno pada deszcz?",
        "answer": "Fałsz ❌",
        "options": ["Prawda ✅", "Fałsz ❌"],
        "explanation": "FAŁSZ! Ulica może być mokra z innego powodu (np. polewaczka). To błąd logiczny!",
        "hints": ["Czy mokra ulica MUSI oznaczać deszcz?"],
    },
]
