"""KidCoder – Math problems: multiplication & division for ages 7-8."""

MATH_PROBLEMS = [
    # ---- MULTIPLICATION ×2 ----
    {
        "id": 1,
        "title": "📖 Mnożenie przez 2",
        "description": "NAUKA: Masz 3 pary skarpetek. Ile skarpetek masz razem?",
        "type": "multiply",
        "visual": "🧦🧦 🧦🧦 🧦🧦",
        "problem": "3 × 2 = ?",
        "a": 3, "b": 2,
        "answer": 6,
        "options": [4, 5, 6, 8],
        "explanation": "3 × 2 = 6. Trzy pary to 3 grupy po 2 skarpetki: 2+2+2 = 6!",
        "hints": ["Policz skarpetki po 2: 2, 4, 6", "3 × 2 = 2 + 2 + 2"],
    },
    {
        "id": 2,
        "title": "🧪 Test: ×2",
        "description": "TEST: Ile to 4 × 2?",
        "type": "multiply",
        "visual": "⭐⭐ ⭐⭐ ⭐⭐ ⭐⭐",
        "problem": "4 × 2 = ?",
        "a": 4, "b": 2,
        "answer": 8,
        "options": [6, 7, 8, 10],
        "explanation": "4 × 2 = 8. Cztery grupy po 2: 2+2+2+2 = 8!",
        "hints": ["Licz po 2: 2, 4, 6, 8"],
    },
    # ---- MULTIPLICATION ×3 ----
    {
        "id": 3,
        "title": "📖 Mnożenie przez 3",
        "description": "NAUKA: Masz 2 trójkąty. Ile boków mają razem?",
        "type": "multiply",
        "visual": "🔺🔺🔺 🔺🔺🔺",
        "problem": "2 × 3 = ?",
        "a": 2, "b": 3,
        "answer": 6,
        "options": [5, 6, 7, 9],
        "explanation": "2 × 3 = 6. Dwa trójkąty mają 3+3 = 6 boków!",
        "hints": ["Każdy trójkąt ma 3 boki", "3 + 3 = ?"],
    },
    {
        "id": 4,
        "title": "🧪 Test: ×3",
        "description": "TEST: Ile to 4 × 3?",
        "type": "multiply",
        "visual": "🍎🍎🍎 🍎🍎🍎 🍎🍎🍎 🍎🍎🍎",
        "problem": "4 × 3 = ?",
        "a": 4, "b": 3,
        "answer": 12,
        "options": [9, 10, 12, 15],
        "explanation": "4 × 3 = 12. Cztery grupy po 3: 3+3+3+3 = 12!",
        "hints": ["Licz po 3: 3, 6, 9, 12"],
    },
    # ---- MULTIPLICATION ×4 ----
    {
        "id": 5,
        "title": "📖 Mnożenie przez 4",
        "description": "NAUKA: Samochód ma 4 koła. Ile kół mają 2 samochody?",
        "type": "multiply",
        "visual": "🚗⚙️⚙️⚙️⚙️ 🚗⚙️⚙️⚙️⚙️",
        "problem": "2 × 4 = ?",
        "a": 2, "b": 4,
        "answer": 8,
        "options": [6, 7, 8, 10],
        "explanation": "2 × 4 = 8. Dwa samochody mają 4+4 = 8 kół!",
        "hints": ["Jeden samochód ma 4 koła", "4 + 4 = ?"],
    },
    {
        "id": 6,
        "title": "🧪 Test: ×4",
        "description": "TEST: Ile to 3 × 4?",
        "type": "multiply",
        "visual": "🌸🌸🌸🌸 🌸🌸🌸🌸 🌸🌸🌸🌸",
        "problem": "3 × 4 = ?",
        "a": 3, "b": 4,
        "answer": 12,
        "options": [8, 10, 12, 16],
        "explanation": "3 × 4 = 12. Trzy grupy po 4: 4+4+4 = 12!",
        "hints": ["Licz po 4: 4, 8, 12"],
    },
    # ---- MULTIPLICATION ×5 ----
    {
        "id": 7,
        "title": "📖 Mnożenie przez 5",
        "description": "NAUKA: Ręka ma 5 palców. Ile palców mają 3 ręce?",
        "type": "multiply",
        "visual": "🖐️🖐️🖐️",
        "problem": "3 × 5 = ?",
        "a": 3, "b": 5,
        "answer": 15,
        "options": [10, 12, 15, 20],
        "explanation": "3 × 5 = 15. Trzy ręce mają 5+5+5 = 15 palców!",
        "hints": ["Jedna ręka ma 5 palców", "Licz po 5: 5, 10, 15"],
    },
    {
        "id": 8,
        "title": "🧪 Test: ×5",
        "description": "TEST: Ile to 4 × 5?",
        "type": "multiply",
        "visual": "⭐⭐⭐⭐⭐ ⭐⭐⭐⭐⭐ ⭐⭐⭐⭐⭐ ⭐⭐⭐⭐⭐",
        "problem": "4 × 5 = ?",
        "a": 4, "b": 5,
        "answer": 20,
        "options": [15, 18, 20, 25],
        "explanation": "4 × 5 = 20. Cztery grupy po 5: 5+5+5+5 = 20!",
        "hints": ["Licz po 5: 5, 10, 15, 20"],
    },
    # ---- MIXED MULTIPLICATION ----
    {
        "id": 9,
        "title": "📖 Mieszane mnożenie",
        "description": "NAUKA: Ile to 5 × 3?",
        "type": "multiply",
        "visual": "🍕🍕🍕 🍕🍕🍕 🍕🍕🍕 🍕🍕🍕 🍕🍕🍕",
        "problem": "5 × 3 = ?",
        "a": 5, "b": 3,
        "answer": 15,
        "options": [12, 13, 15, 18],
        "explanation": "5 × 3 = 15. Pięć grup po 3: 3+3+3+3+3 = 15!",
        "hints": ["Licz po 3: 3, 6, 9, 12, 15"],
    },
    {
        "id": 10,
        "title": "🧪 Test: Mieszane",
        "description": "TEST: Ile to 5 × 4?",
        "type": "multiply",
        "visual": "🎁🎁🎁🎁 🎁🎁🎁🎁 🎁🎁🎁🎁 🎁🎁🎁🎁 🎁🎁🎁🎁",
        "problem": "5 × 4 = ?",
        "a": 5, "b": 4,
        "answer": 20,
        "options": [16, 18, 20, 25],
        "explanation": "5 × 4 = 20. Pięć grup po 4: 4+4+4+4+4 = 20!",
        "hints": ["Licz po 4: 4, 8, 12, 16, 20"],
    },
    # ---- DIVISION ÷2 ----
    {
        "id": 11,
        "title": "📖 Dzielenie przez 2",
        "description": "NAUKA: Masz 8 ciastek i chcesz je podzielić równo na 2 talerze. Ile ciastek na każdym talerzu?",
        "type": "divide",
        "visual": "🍪🍪🍪🍪🍪🍪🍪🍪",
        "problem": "8 ÷ 2 = ?",
        "a": 8, "b": 2,
        "answer": 4,
        "options": [2, 3, 4, 6],
        "explanation": "8 ÷ 2 = 4. Osiem ciastek na 2 talerze to po 4 na każdym!",
        "hints": ["Podziel 8 na dwie równe grupy", "4 + 4 = 8"],
    },
    {
        "id": 12,
        "title": "🧪 Test: ÷2",
        "description": "TEST: Ile to 10 ÷ 2?",
        "type": "divide",
        "visual": "🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬",
        "problem": "10 ÷ 2 = ?",
        "a": 10, "b": 2,
        "answer": 5,
        "options": [3, 4, 5, 6],
        "explanation": "10 ÷ 2 = 5. Dziesięć cukierków po równo na 2: po 5 każde!",
        "hints": ["5 + 5 = 10"],
    },
    # ---- DIVISION ÷3 ----
    {
        "id": 13,
        "title": "📖 Dzielenie przez 3",
        "description": "NAUKA: Masz 9 jabłek i 3 kosze. Ile jabłek w każdym koszu?",
        "type": "divide",
        "visual": "🍎🍎🍎🍎🍎🍎🍎🍎🍎",
        "problem": "9 ÷ 3 = ?",
        "a": 9, "b": 3,
        "answer": 3,
        "options": [2, 3, 4, 6],
        "explanation": "9 ÷ 3 = 3. Dziewięć jabłek w 3 koszach to po 3 w każdym!",
        "hints": ["3 × 3 = 9, więc 9 ÷ 3 = 3"],
    },
    {
        "id": 14,
        "title": "🧪 Test: ÷3",
        "description": "TEST: Ile to 12 ÷ 3?",
        "type": "divide",
        "visual": "🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟",
        "problem": "12 ÷ 3 = ?",
        "a": 12, "b": 3,
        "answer": 4,
        "options": [3, 4, 5, 6],
        "explanation": "12 ÷ 3 = 4. Dwanaście gwiazdek w 3 grupach to po 4!",
        "hints": ["3 × 4 = 12, więc 12 ÷ 3 = 4"],
    },
    # ---- DIVISION ÷4 ----
    {
        "id": 15,
        "title": "📖 Dzielenie przez 4",
        "description": "NAUKA: Masz 12 kredek i 4 pudełka. Ile kredek w każdym pudełku?",
        "type": "divide",
        "visual": "🖍️🖍️🖍️🖍️🖍️🖍️🖍️🖍️🖍️🖍️🖍️🖍️",
        "problem": "12 ÷ 4 = ?",
        "a": 12, "b": 4,
        "answer": 3,
        "options": [2, 3, 4, 6],
        "explanation": "12 ÷ 4 = 3. Dwanaście kredek w 4 pudełkach to po 3!",
        "hints": ["4 × 3 = 12, więc 12 ÷ 4 = 3"],
    },
    {
        "id": 16,
        "title": "🧪 Test: ÷4",
        "description": "TEST: Ile to 16 ÷ 4?",
        "type": "divide",
        "visual": "🐣🐣🐣🐣🐣🐣🐣🐣🐣🐣🐣🐣🐣🐣🐣🐣",
        "problem": "16 ÷ 4 = ?",
        "a": 16, "b": 4,
        "answer": 4,
        "options": [3, 4, 5, 8],
        "explanation": "16 ÷ 4 = 4. Szesnaście piskląt w 4 gniazdach to po 4!",
        "hints": ["4 × 4 = 16, więc 16 ÷ 4 = 4"],
    },
    # ---- DIVISION ÷5 ----
    {
        "id": 17,
        "title": "📖 Dzielenie przez 5",
        "description": "NAUKA: Masz 15 balonów i 5 dzieci. Ile balonów dostanie każde dziecko?",
        "type": "divide",
        "visual": "🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈",
        "problem": "15 ÷ 5 = ?",
        "a": 15, "b": 5,
        "answer": 3,
        "options": [2, 3, 4, 5],
        "explanation": "15 ÷ 5 = 3. Piętnaście balonów na 5 dzieci to po 3 balony!",
        "hints": ["5 × 3 = 15, więc 15 ÷ 5 = 3"],
    },
    {
        "id": 18,
        "title": "🧪 Test: ÷5",
        "description": "TEST: Ile to 20 ÷ 5?",
        "type": "divide",
        "visual": "🍭🍭🍭🍭🍭🍭🍭🍭🍭🍭🍭🍭🍭🍭🍭🍭🍭🍭🍭🍭",
        "problem": "20 ÷ 5 = ?",
        "a": 20, "b": 5,
        "answer": 4,
        "options": [3, 4, 5, 10],
        "explanation": "20 ÷ 5 = 4. Dwadzieścia lizaków na 5 grup to po 4!",
        "hints": ["5 × 4 = 20, więc 20 ÷ 5 = 4"],
    },
    # ---- CHALLENGE ----
    {
        "id": 19,
        "title": "🏆 Wyzwanie: ×2 i ×3",
        "description": "WYZWANIE: Ile to 5 × 2 i 2 × 3 razem?",
        "type": "multiply",
        "visual": "🎯🎯 🎯🎯 🎯🎯 🎯🎯 🎯🎯   🔵🔵🔵 🔵🔵🔵",
        "problem": "5×2 + 2×3 = ?",
        "a": 5, "b": 2,
        "answer": 16,
        "options": [12, 14, 16, 20],
        "explanation": "5×2 = 10, a 2×3 = 6, więc 10 + 6 = 16!",
        "hints": ["Najpierw oblicz 5×2, potem 2×3", "10 + 6 = ?"],
    },
    {
        "id": 20,
        "title": "🏆 Wyzwanie: Dzielenie",
        "description": "WYZWANIE: Masz 20 cukierków. Dajesz 4 przyjaciołom po równo. Ile dostaje każdy?",
        "type": "divide",
        "visual": "🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬",
        "problem": "20 ÷ 4 = ?",
        "a": 20, "b": 4,
        "answer": 5,
        "options": [4, 5, 6, 10],
        "explanation": "20 ÷ 4 = 5. Dwadzieścia cukierków na 4 przyjaciół to po 5 każdy!",
        "hints": ["4 × 5 = 20, więc 20 ÷ 4 = 5"],
    },
]
