"""KidCoder – Math problems: multiplication & division for ages 7-8.

Visual types:
  groups  — N boxes each containing M emoji (multiplication)
  split   — M emoji total split into N buckets (division)
  array   — rows × cols grid (square-ish products)
  number_line — jump on a number line (×10 / skip-counting)
"""

MATH_PROBLEMS = [

    # ══════════════════════════════════════════
    #  MNOŻENIE PRZEZ 2  (×2)
    # ══════════════════════════════════════════
    {
        "id": 1,
        "title": "📖 Co to jest mnożenie?",
        "lesson_type": "lesson",
        "type": "multiply",
        "table": 2,
        "a": 3, "b": 2,
        "problem": "3 × 2 = ?",
        "answer": 6,
        "options": [4, 5, 6, 8],
        "visual_type": "groups",
        "visual_emoji": "🧦",
        "visual_groups": 3,
        "visual_per_group": 2,
        "visual_group_label": "Para",
        "story": "Masz 3 pary skarpetek. Każda para to 2 skarpetki.",
        "lesson_text": "Mnożenie to szybkie dodawanie grup! 3 × 2 znaczy: 3 grupy, po 2 skarpetki w każdej.",
        "explanation": "3 × 2 = 6\nTrzy pary skarpetek:\n2 + 2 + 2 = 6 skarpetek!",
        "hints": ["Policz skarpetki po 2: 2, 4, 6", "3 × 2 znaczy: dodaj 2, trzy razy"],
    },
    {
        "id": 2,
        "title": "📖 Liczymy po 2!",
        "lesson_type": "lesson",
        "type": "multiply",
        "table": 2,
        "a": 4, "b": 2,
        "problem": "4 × 2 = ?",
        "answer": 8,
        "options": [6, 7, 8, 10],
        "visual_type": "groups",
        "visual_emoji": "🎈",
        "visual_groups": 4,
        "visual_per_group": 2,
        "visual_group_label": "Pęczek",
        "story": "Każde dziecko dostało 2 balony. Jest 4 dzieci. Ile balonów razem?",
        "lesson_text": "Licz po 2: 2 → 4 → 6 → 8. Za każdą grupą dodajemy 2!",
        "explanation": "4 × 2 = 8\nCztery grupy po 2: 2+2+2+2 = 8 balonów!",
        "hints": ["Licz po 2: 2, 4, 6, 8", "4 grupy po 2 to jakbyś 4 razy dodał 2"],
    },
    {
        "id": 3,
        "title": "🏃 Ćwiczenie: ×2",
        "lesson_type": "practice",
        "type": "multiply",
        "table": 2,
        "a": 5, "b": 2,
        "problem": "5 × 2 = ?",
        "answer": 10,
        "options": [8, 9, 10, 12],
        "visual_type": "groups",
        "visual_emoji": "🍎",
        "visual_groups": 5,
        "visual_per_group": 2,
        "visual_group_label": "Koszyk",
        "story": "W 5 koszyczkach leżą po 2 jabłka. Ile jabłek razem?",
        "lesson_text": "Licz po 2: 2, 4, 6, 8, 10. Pięć kroków po 2!",
        "explanation": "5 × 2 = 10\nPięć koszyczków po 2 jabłka: 2+2+2+2+2 = 10!",
        "hints": ["Licz po 2: 2, 4, 6, 8, 10"],
    },
    {
        "id": 4,
        "title": "🧪 Test: ×2",
        "lesson_type": "test",
        "type": "multiply",
        "table": 2,
        "a": 6, "b": 2,
        "problem": "6 × 2 = ?",
        "answer": 12,
        "options": [10, 11, 12, 14],
        "visual_type": "groups",
        "visual_emoji": "⭐",
        "visual_groups": 6,
        "visual_per_group": 2,
        "visual_group_label": "Zestaw",
        "story": "6 zestawów po 2 gwiazdki. Ile gwiazdek razem?",
        "lesson_text": None,
        "explanation": "6 × 2 = 12\nSześć grup po 2: 2+2+2+2+2+2 = 12!",
        "hints": ["Licz po 2 aż do 6. kroku"],
    },

    # ══════════════════════════════════════════
    #  MNOŻENIE PRZEZ 3  (×3)
    # ══════════════════════════════════════════
    {
        "id": 5,
        "title": "📖 Mnożenie przez 3",
        "lesson_type": "lesson",
        "type": "multiply",
        "table": 3,
        "a": 2, "b": 3,
        "problem": "2 × 3 = ?",
        "answer": 6,
        "options": [4, 5, 6, 9],
        "visual_type": "groups",
        "visual_emoji": "🔺",
        "visual_groups": 2,
        "visual_per_group": 3,
        "visual_group_label": "Trójkąt",
        "story": "Trójkąt ma 3 boki. Masz 2 trójkąty – ile boków razem?",
        "lesson_text": "Każdy trójkąt ma 3 boki. 2 trójkąty → 3 + 3 = 6 boków razem!",
        "explanation": "2 × 3 = 6\nDwa trójkąty mają: 3 + 3 = 6 boków!",
        "hints": ["Trójkąt ma 3 boki", "3 + 3 = ?"],
    },
    {
        "id": 6,
        "title": "📖 Liczymy po 3!",
        "lesson_type": "lesson",
        "type": "multiply",
        "table": 3,
        "a": 3, "b": 3,
        "problem": "3 × 3 = ?",
        "answer": 9,
        "options": [6, 7, 9, 12],
        "visual_type": "groups",
        "visual_emoji": "🌸",
        "visual_groups": 3,
        "visual_per_group": 3,
        "visual_group_label": "Bukiecik",
        "story": "Zebrałeś 3 bukieciki, każdy z 3 kwiatkami. Ile kwiatków razem?",
        "lesson_text": "Licz po 3: 3 → 6 → 9. Za każdą grupą dodajemy 3!",
        "explanation": "3 × 3 = 9\nTrzy bukieciki po 3 kwiatki: 3+3+3 = 9 kwiatków!",
        "hints": ["Licz po 3: 3, 6, 9"],
    },
    {
        "id": 7,
        "title": "🏃 Ćwiczenie: ×3",
        "lesson_type": "practice",
        "type": "multiply",
        "table": 3,
        "a": 4, "b": 3,
        "problem": "4 × 3 = ?",
        "answer": 12,
        "options": [9, 10, 12, 15],
        "visual_type": "groups",
        "visual_emoji": "🍪",
        "visual_groups": 4,
        "visual_per_group": 3,
        "visual_group_label": "Talerz",
        "story": "Na 4 talerzach leżą po 3 ciastka. Ile ciastek razem?",
        "lesson_text": "Licz po 3: 3, 6, 9, 12. Cztery kroki po 3!",
        "explanation": "4 × 3 = 12\nCztery talerze po 3 ciastka: 3+3+3+3 = 12!",
        "hints": ["Licz po 3: 3, 6, 9, 12"],
    },
    {
        "id": 8,
        "title": "🧪 Test: ×3",
        "lesson_type": "test",
        "type": "multiply",
        "table": 3,
        "a": 5, "b": 3,
        "problem": "5 × 3 = ?",
        "answer": 15,
        "options": [12, 13, 15, 18],
        "visual_type": "groups",
        "visual_emoji": "🔵",
        "visual_groups": 5,
        "visual_per_group": 3,
        "visual_group_label": "Rząd",
        "story": "5 rzędów po 3 niebieskie kółka. Ile kółek razem?",
        "lesson_text": None,
        "explanation": "5 × 3 = 15\nPięć rzędów po 3: 3+3+3+3+3 = 15!",
        "hints": ["Licz po 3: 3, 6, 9, 12, 15"],
    },

    # ══════════════════════════════════════════
    #  MNOŻENIE PRZEZ 4  (×4)
    # ══════════════════════════════════════════
    {
        "id": 9,
        "title": "📖 Mnożenie przez 4",
        "lesson_type": "lesson",
        "type": "multiply",
        "table": 4,
        "a": 2, "b": 4,
        "problem": "2 × 4 = ?",
        "answer": 8,
        "options": [6, 7, 8, 10],
        "visual_type": "groups",
        "visual_emoji": "🚗",
        "visual_groups": 2,
        "visual_per_group": 4,
        "visual_group_label": "Auto",
        "story": "Samochód ma 4 koła. Ile kół mają 2 samochody?",
        "lesson_text": "Każdy samochód ma 4 koła! 2 samochody → 4 + 4 = 8 kół razem.",
        "explanation": "2 × 4 = 8\nDwa samochody: 4 koła + 4 koła = 8 kół!",
        "hints": ["Jeden samochód ma 4 koła", "4 + 4 = ?"],
    },
    {
        "id": 10,
        "title": "📖 Kocie łapy!",
        "lesson_type": "lesson",
        "type": "multiply",
        "table": 4,
        "a": 3, "b": 4,
        "problem": "3 × 4 = ?",
        "answer": 12,
        "options": [8, 10, 12, 16],
        "visual_type": "groups",
        "visual_emoji": "🐱",
        "visual_groups": 3,
        "visual_per_group": 4,
        "visual_group_label": "Kotek",
        "story": "Kot ma 4 łapy. Ile łap mają 3 koty?",
        "lesson_text": "Każdy kotek ma 4 łapy! 3 koty → 4 + 4 + 4 = 12 łap razem.",
        "explanation": "3 × 4 = 12\nTrzy koty: 4+4+4 = 12 łap!",
        "hints": ["Licz po 4: 4, 8, 12"],
    },
    {
        "id": 11,
        "title": "🏃 Ćwiczenie: ×4",
        "lesson_type": "practice",
        "type": "multiply",
        "table": 4,
        "a": 4, "b": 4,
        "problem": "4 × 4 = ?",
        "answer": 16,
        "options": [12, 14, 16, 20],
        "visual_type": "array",
        "visual_emoji": "🌺",
        "visual_rows": 4,
        "visual_cols": 4,
        "story": "Ogród ma 4 rzędy po 4 kwiatki. Ile kwiatków razem?",
        "lesson_text": "4 rzędy × 4 kolumny = siatka 4 na 4. Policz wszystkie!",
        "explanation": "4 × 4 = 16\nCztery rzędy po 4 kwiatki: 4+4+4+4 = 16!",
        "hints": ["Policz rząd po rzędzie: 4, 8, 12, 16"],
    },
    {
        "id": 12,
        "title": "🧪 Test: ×4",
        "lesson_type": "test",
        "type": "multiply",
        "table": 4,
        "a": 5, "b": 4,
        "problem": "5 × 4 = ?",
        "answer": 20,
        "options": [16, 18, 20, 24],
        "visual_type": "groups",
        "visual_emoji": "✋",
        "visual_groups": 5,
        "visual_per_group": 4,
        "visual_group_label": "Zestaw",
        "story": "5 zestawów po 4 naklejki. Ile naklejek razem?",
        "lesson_text": None,
        "explanation": "5 × 4 = 20\nPięć zestawów po 4: 4+4+4+4+4 = 20!",
        "hints": ["Licz po 4: 4, 8, 12, 16, 20"],
    },

    # ══════════════════════════════════════════
    #  MNOŻENIE PRZEZ 5  (×5)
    # ══════════════════════════════════════════
    {
        "id": 13,
        "title": "📖 Mnożenie przez 5",
        "lesson_type": "lesson",
        "type": "multiply",
        "table": 5,
        "a": 2, "b": 5,
        "problem": "2 × 5 = ?",
        "answer": 10,
        "options": [8, 9, 10, 12],
        "visual_type": "groups",
        "visual_emoji": "🖐️",
        "visual_groups": 2,
        "visual_per_group": 5,
        "visual_group_label": "Rączka",
        "story": "Rączka ma 5 palców. Ile palców mają 2 rączki?",
        "lesson_text": "Każda rączka ma 5 palców! 2 rączki → 5 + 5 = 10 palców razem.",
        "explanation": "2 × 5 = 10\nDwie rączki: 5 + 5 = 10 palców!",
        "hints": ["Jedna rączka = 5 palców", "5 + 5 = ?"],
    },
    {
        "id": 14,
        "title": "📖 Liczymy po 5!",
        "lesson_type": "lesson",
        "type": "multiply",
        "table": 5,
        "a": 3, "b": 5,
        "problem": "3 × 5 = ?",
        "answer": 15,
        "options": [10, 12, 15, 20],
        "visual_type": "groups",
        "visual_emoji": "🌟",
        "visual_groups": 3,
        "visual_per_group": 5,
        "visual_group_label": "Rząd",
        "story": "3 rzędy po 5 gwiazdek. Ile gwiazdek razem?",
        "lesson_text": "Licz po 5: 5 → 10 → 15. Za każdą grupą dodajemy 5!",
        "explanation": "3 × 5 = 15\nTrzy rzędy po 5: 5+5+5 = 15 gwiazdek!",
        "hints": ["Licz po 5: 5, 10, 15"],
    },
    {
        "id": 15,
        "title": "🏃 Ćwiczenie: ×5",
        "lesson_type": "practice",
        "type": "multiply",
        "table": 5,
        "a": 4, "b": 5,
        "problem": "4 × 5 = ?",
        "answer": 20,
        "options": [15, 18, 20, 25],
        "visual_type": "groups",
        "visual_emoji": "🍬",
        "visual_groups": 4,
        "visual_per_group": 5,
        "visual_group_label": "Torebka",
        "story": "4 torebki po 5 cukierków. Ile cukierków razem?",
        "lesson_text": "Licz po 5: 5, 10, 15, 20. Cztery kroki po 5!",
        "explanation": "4 × 5 = 20\nCztery torebki po 5: 5+5+5+5 = 20!",
        "hints": ["Licz po 5: 5, 10, 15, 20"],
    },
    {
        "id": 16,
        "title": "🧪 Test: ×5",
        "lesson_type": "test",
        "type": "multiply",
        "table": 5,
        "a": 5, "b": 5,
        "problem": "5 × 5 = ?",
        "answer": 25,
        "options": [20, 22, 25, 30],
        "visual_type": "array",
        "visual_emoji": "🔵",
        "visual_rows": 5,
        "visual_cols": 5,
        "story": "Siatka 5 na 5 kółek. Ile kółek razem?",
        "lesson_text": None,
        "explanation": "5 × 5 = 25\nPięć rzędów po 5: 5+5+5+5+5 = 25!",
        "hints": ["Policz rząd po rzędzie: 5, 10, 15, 20, 25"],
    },

    # ══════════════════════════════════════════
    #  MNOŻENIE PRZEZ 10  (×10)
    # ══════════════════════════════════════════
    {
        "id": 17,
        "title": "📖 Mnożenie przez 10",
        "lesson_type": "lesson",
        "type": "multiply",
        "table": 10,
        "a": 2, "b": 10,
        "problem": "2 × 10 = ?",
        "answer": 20,
        "options": [12, 15, 20, 25],
        "visual_type": "number_line",
        "visual_jump": 10,
        "visual_jumps": 2,
        "visual_end": 20,
        "story": "Masz 2 dziesiątek. Ile to razem?",
        "lesson_text": "Mnożenie przez 10 jest super proste! Dopisz zero na końcu: 2 × 10 = 20.",
        "explanation": "2 × 10 = 20\nDwie dziesiątki: 10 + 10 = 20!",
        "hints": ["Każdy skok to +10", "10 + 10 = 20"],
    },
    {
        "id": 18,
        "title": "🧪 Test: ×10",
        "lesson_type": "test",
        "type": "multiply",
        "table": 10,
        "a": 3, "b": 10,
        "problem": "3 × 10 = ?",
        "answer": 30,
        "options": [20, 25, 30, 35],
        "visual_type": "number_line",
        "visual_jump": 10,
        "visual_jumps": 3,
        "visual_end": 30,
        "story": "Trzy dziesiątki. Ile to razem?",
        "lesson_text": None,
        "explanation": "3 × 10 = 30\nTrzy dziesiątki: 10+10+10 = 30!",
        "hints": ["Skoki po 10: 10, 20, 30"],
    },

    # ══════════════════════════════════════════
    #  WYZWANIA MNOŻENIA
    # ══════════════════════════════════════════
    {
        "id": 19,
        "title": "🏆 Wyzwanie: Sklep z zabawkami",
        "lesson_type": "challenge",
        "type": "multiply",
        "table": 3,
        "a": 4, "b": 3,
        "problem": "4 × 3 = ?",
        "answer": 12,
        "options": [9, 11, 12, 15],
        "visual_type": "groups",
        "visual_emoji": "🎁",
        "visual_groups": 4,
        "visual_per_group": 3,
        "visual_group_label": "Pudełko",
        "story": "W sklepie są 4 pudełka prezentów. W każdym pudełku kryją się 3 zabawki. Ile zabawek razem?",
        "lesson_text": "Pamiętaj: liczba grup × liczba w każdej grupie = razem!",
        "explanation": "4 × 3 = 12\nCztery pudełka po 3 zabawki: 3+3+3+3 = 12!",
        "hints": ["4 grupy po 3: 3, 6, 9, 12"],
    },
    {
        "id": 20,
        "title": "🏆 Wyzwanie: Wielka siatka",
        "lesson_type": "challenge",
        "type": "multiply",
        "table": 5,
        "a": 3, "b": 4,
        "problem": "3 × 4 = ?",
        "answer": 12,
        "options": [10, 11, 12, 15],
        "visual_type": "array",
        "visual_emoji": "🪙",
        "visual_rows": 3,
        "visual_cols": 4,
        "story": "Na stole leżą monety w 3 rzędach po 4. Ile monet razem?",
        "lesson_text": "W siatce: wiersze × kolumny = razem! 3 wiersze × 4 kolumny.",
        "explanation": "3 × 4 = 12\nTrzy wiersze po 4 monety: 4+4+4 = 12!",
        "hints": ["Policz wiersz po wierszu: 4, 8, 12"],
    },

    # ══════════════════════════════════════════
    #  DZIELENIE PRZEZ 2  (÷2)
    # ══════════════════════════════════════════
    {
        "id": 21,
        "title": "📖 Co to jest dzielenie?",
        "lesson_type": "lesson",
        "type": "divide",
        "table": 2,
        "a": 6, "b": 2,
        "problem": "6 ÷ 2 = ?",
        "answer": 3,
        "options": [2, 3, 4, 6],
        "visual_type": "split",
        "visual_emoji": "🍪",
        "visual_total": 6,
        "visual_groups": 2,
        "visual_group_label": "Talerz",
        "story": "Masz 6 ciasteczek i 2 talerze. Podziel po równo!",
        "lesson_text": "Dzielenie to równy podział! 6 ÷ 2 = podziel 6 ciastek na 2 talerze po równo.",
        "explanation": "6 ÷ 2 = 3\nSześć ciastek na 2 talerze: po 3 na każdym!",
        "hints": ["Rozłóż ciastka po jednym na każdy talerz", "3 + 3 = 6"],
    },
    {
        "id": 22,
        "title": "📖 Połowa to ÷2!",
        "lesson_type": "lesson",
        "type": "divide",
        "table": 2,
        "a": 8, "b": 2,
        "problem": "8 ÷ 2 = ?",
        "answer": 4,
        "options": [2, 3, 4, 6],
        "visual_type": "split",
        "visual_emoji": "⭐",
        "visual_total": 8,
        "visual_groups": 2,
        "visual_group_label": "Zestaw",
        "story": "8 gwiazdek podzielone na 2 zestawy po równo. Ile w każdym?",
        "lesson_text": "Dzielenie przez 2 to znajdowanie połowy! Połowa z 8 to 4.",
        "explanation": "8 ÷ 2 = 4\nOsiem gwiazdek na 2 zestawy: po 4 w każdym!",
        "hints": ["Połowa z 8 to ?", "4 + 4 = 8"],
    },
    {
        "id": 23,
        "title": "🏃 Ćwiczenie: ÷2",
        "lesson_type": "practice",
        "type": "divide",
        "table": 2,
        "a": 10, "b": 2,
        "problem": "10 ÷ 2 = ?",
        "answer": 5,
        "options": [3, 4, 5, 6],
        "visual_type": "split",
        "visual_emoji": "🍬",
        "visual_total": 10,
        "visual_groups": 2,
        "visual_group_label": "Torebka",
        "story": "10 cukierków do 2 torebek po równo. Ile w każdej?",
        "lesson_text": None,
        "explanation": "10 ÷ 2 = 5\nDziesięć cukierków na 2 torebki: po 5 w każdej!",
        "hints": ["5 + 5 = 10, więc 10 ÷ 2 = 5"],
    },
    {
        "id": 24,
        "title": "🧪 Test: ÷2",
        "lesson_type": "test",
        "type": "divide",
        "table": 2,
        "a": 12, "b": 2,
        "problem": "12 ÷ 2 = ?",
        "answer": 6,
        "options": [4, 5, 6, 8],
        "visual_type": "split",
        "visual_emoji": "🎈",
        "visual_total": 12,
        "visual_groups": 2,
        "visual_group_label": "Pęczek",
        "story": "12 balonów na 2 pęczki po równo. Ile w każdym pęczku?",
        "lesson_text": None,
        "explanation": "12 ÷ 2 = 6\nDwanaście balonów na 2 pęczki: po 6 w każdym!",
        "hints": ["6 + 6 = 12, więc 12 ÷ 2 = 6"],
    },

    # ══════════════════════════════════════════
    #  DZIELENIE PRZEZ 3  (÷3)
    # ══════════════════════════════════════════
    {
        "id": 25,
        "title": "📖 Dzielenie przez 3",
        "lesson_type": "lesson",
        "type": "divide",
        "table": 3,
        "a": 9, "b": 3,
        "problem": "9 ÷ 3 = ?",
        "answer": 3,
        "options": [2, 3, 4, 6],
        "visual_type": "split",
        "visual_emoji": "🍓",
        "visual_total": 9,
        "visual_groups": 3,
        "visual_group_label": "Koszyk",
        "story": "Masz 9 truskawek i 3 koszyki. Podziel po równo!",
        "lesson_text": "Dzielimy 9 truskawek na 3 koszyki. Kładziemy po jednej na raz, aż nie zostanie żadna!",
        "explanation": "9 ÷ 3 = 3\nDziewięć truskawek na 3 koszyki: po 3 w każdym!",
        "hints": ["3 × 3 = 9, więc 9 ÷ 3 = 3", "Rozdawaj po jednej: 1, 2, 3 do każdego koszyka"],
    },
    {
        "id": 26,
        "title": "📖 Trzy równe grupy",
        "lesson_type": "lesson",
        "type": "divide",
        "table": 3,
        "a": 6, "b": 3,
        "problem": "6 ÷ 3 = ?",
        "answer": 2,
        "options": [1, 2, 3, 4],
        "visual_type": "split",
        "visual_emoji": "🌸",
        "visual_total": 6,
        "visual_groups": 3,
        "visual_group_label": "Wazon",
        "story": "6 kwiatków do 3 wazonów po równo. Ile kwiatków w każdym wazonie?",
        "lesson_text": "6 ÷ 3 = 2. Dzielimy 6 na 3 równe grupy. Każda dostaje 2!",
        "explanation": "6 ÷ 3 = 2\nSześć kwiatków na 3 wazony: po 2 w każdym!",
        "hints": ["2 + 2 + 2 = 6", "3 × 2 = 6, więc 6 ÷ 3 = 2"],
    },
    {
        "id": 27,
        "title": "🏃 Ćwiczenie: ÷3",
        "lesson_type": "practice",
        "type": "divide",
        "table": 3,
        "a": 12, "b": 3,
        "problem": "12 ÷ 3 = ?",
        "answer": 4,
        "options": [3, 4, 5, 6],
        "visual_type": "split",
        "visual_emoji": "🎨",
        "visual_total": 12,
        "visual_groups": 3,
        "visual_group_label": "Zestaw",
        "story": "12 kredek do 3 zestawów po równo. Ile w każdym zestawie?",
        "lesson_text": None,
        "explanation": "12 ÷ 3 = 4\nDwanaście kredek na 3 zestawy: po 4 w każdym!",
        "hints": ["3 × 4 = 12, więc 12 ÷ 3 = 4"],
    },
    {
        "id": 28,
        "title": "🧪 Test: ÷3",
        "lesson_type": "test",
        "type": "divide",
        "table": 3,
        "a": 15, "b": 3,
        "problem": "15 ÷ 3 = ?",
        "answer": 5,
        "options": [4, 5, 6, 8],
        "visual_type": "split",
        "visual_emoji": "⚽",
        "visual_total": 15,
        "visual_groups": 3,
        "visual_group_label": "Drużyna",
        "story": "15 piłek na 3 drużyny po równo. Ile piłek na drużynę?",
        "lesson_text": None,
        "explanation": "15 ÷ 3 = 5\nPiętnaście piłek na 3 drużyny: po 5 na drużynę!",
        "hints": ["3 × 5 = 15, więc 15 ÷ 3 = 5"],
    },

    # ══════════════════════════════════════════
    #  DZIELENIE PRZEZ 4  (÷4)
    # ══════════════════════════════════════════
    {
        "id": 29,
        "title": "📖 Dzielenie przez 4",
        "lesson_type": "lesson",
        "type": "divide",
        "table": 4,
        "a": 8, "b": 4,
        "problem": "8 ÷ 4 = ?",
        "answer": 2,
        "options": [1, 2, 3, 4],
        "visual_type": "split",
        "visual_emoji": "🍎",
        "visual_total": 8,
        "visual_groups": 4,
        "visual_group_label": "Kosz",
        "story": "Masz 8 jabłek i 4 kosze. Podziel po równo!",
        "lesson_text": "Dzielimy 8 jabłek na 4 kosze. Każdy kosz dostaje 2 jabłka!",
        "explanation": "8 ÷ 4 = 2\nOsiem jabłek na 4 kosze: po 2 w każdym!",
        "hints": ["4 × 2 = 8, więc 8 ÷ 4 = 2", "2 + 2 + 2 + 2 = 8"],
    },
    {
        "id": 30,
        "title": "📖 Cztery równe grupy",
        "lesson_type": "lesson",
        "type": "divide",
        "table": 4,
        "a": 12, "b": 4,
        "problem": "12 ÷ 4 = ?",
        "answer": 3,
        "options": [2, 3, 4, 6],
        "visual_type": "split",
        "visual_emoji": "🖍️",
        "visual_total": 12,
        "visual_groups": 4,
        "visual_group_label": "Pudełko",
        "story": "12 kredek do 4 pudełek po równo. Ile w każdym pudełku?",
        "lesson_text": "12 ÷ 4 = 3. Dzielimy 12 na 4 równe grupy. Każda dostaje 3!",
        "explanation": "12 ÷ 4 = 3\nDwanaście kredek na 4 pudełka: po 3 w każdym!",
        "hints": ["4 × 3 = 12, więc 12 ÷ 4 = 3"],
    },
    {
        "id": 31,
        "title": "🏃 Ćwiczenie: ÷4",
        "lesson_type": "practice",
        "type": "divide",
        "table": 4,
        "a": 16, "b": 4,
        "problem": "16 ÷ 4 = ?",
        "answer": 4,
        "options": [3, 4, 5, 8],
        "visual_type": "split",
        "visual_emoji": "🐣",
        "visual_total": 16,
        "visual_groups": 4,
        "visual_group_label": "Gniazdko",
        "story": "16 piskląt do 4 gniazdek po równo. Ile piskląt w każdym?",
        "lesson_text": None,
        "explanation": "16 ÷ 4 = 4\nSzesnaście piskląt na 4 gniazdka: po 4 w każdym!",
        "hints": ["4 × 4 = 16, więc 16 ÷ 4 = 4"],
    },
    {
        "id": 32,
        "title": "🧪 Test: ÷4",
        "lesson_type": "test",
        "type": "divide",
        "table": 4,
        "a": 20, "b": 4,
        "problem": "20 ÷ 4 = ?",
        "answer": 5,
        "options": [4, 5, 6, 8],
        "visual_type": "split",
        "visual_emoji": "🍬",
        "visual_total": 20,
        "visual_groups": 4,
        "visual_group_label": "Torebka",
        "story": "20 cukierków na 4 torebki po równo. Ile w każdej?",
        "lesson_text": None,
        "explanation": "20 ÷ 4 = 5\nDwadzieścia cukierków na 4 torebki: po 5 w każdej!",
        "hints": ["4 × 5 = 20, więc 20 ÷ 4 = 5"],
    },

    # ══════════════════════════════════════════
    #  DZIELENIE PRZEZ 5  (÷5)
    # ══════════════════════════════════════════
    {
        "id": 33,
        "title": "📖 Dzielenie przez 5",
        "lesson_type": "lesson",
        "type": "divide",
        "table": 5,
        "a": 10, "b": 5,
        "problem": "10 ÷ 5 = ?",
        "answer": 2,
        "options": [1, 2, 3, 5],
        "visual_type": "split",
        "visual_emoji": "🍭",
        "visual_total": 10,
        "visual_groups": 5,
        "visual_group_label": "Dziecko",
        "story": "Masz 10 lizaków dla 5 dzieci. Podziel po równo!",
        "lesson_text": "Dzielimy 10 lizaków na 5 dzieci. Każde dziecko dostaje 2 lizaki!",
        "explanation": "10 ÷ 5 = 2\nDziesięć lizaków na 5 dzieci: po 2 dla każdego!",
        "hints": ["5 × 2 = 10, więc 10 ÷ 5 = 2", "2 + 2 + 2 + 2 + 2 = 10"],
    },
    {
        "id": 34,
        "title": "📖 Pięć równych grup",
        "lesson_type": "lesson",
        "type": "divide",
        "table": 5,
        "a": 15, "b": 5,
        "problem": "15 ÷ 5 = ?",
        "answer": 3,
        "options": [2, 3, 4, 5],
        "visual_type": "split",
        "visual_emoji": "🎈",
        "visual_total": 15,
        "visual_groups": 5,
        "visual_group_label": "Dziecko",
        "story": "15 balonów na 5 dzieci po równo. Ile balonów dostaje każde dziecko?",
        "lesson_text": "15 ÷ 5 = 3. Dzielimy 15 na 5 równych grup. Każda dostaje 3!",
        "explanation": "15 ÷ 5 = 3\nPiętnaście balonów na 5 dzieci: po 3 balony dla każdego!",
        "hints": ["5 × 3 = 15, więc 15 ÷ 5 = 3"],
    },
    {
        "id": 35,
        "title": "🏃 Ćwiczenie: ÷5",
        "lesson_type": "practice",
        "type": "divide",
        "table": 5,
        "a": 20, "b": 5,
        "problem": "20 ÷ 5 = ?",
        "answer": 4,
        "options": [3, 4, 5, 10],
        "visual_type": "split",
        "visual_emoji": "🌟",
        "visual_total": 20,
        "visual_groups": 5,
        "visual_group_label": "Koperta",
        "story": "20 gwiazdek do 5 kopert po równo. Ile gwiazdek w każdej kopercie?",
        "lesson_text": None,
        "explanation": "20 ÷ 5 = 4\nDwadzieścia gwiazdek na 5 kopert: po 4 w każdej!",
        "hints": ["5 × 4 = 20, więc 20 ÷ 5 = 4"],
    },
    {
        "id": 36,
        "title": "🧪 Test: ÷5",
        "lesson_type": "test",
        "type": "divide",
        "table": 5,
        "a": 25, "b": 5,
        "problem": "25 ÷ 5 = ?",
        "answer": 5,
        "options": [4, 5, 6, 10],
        "visual_type": "split",
        "visual_emoji": "🪙",
        "visual_total": 20,
        "visual_groups": 5,
        "visual_group_label": "Słoik",
        "visual_note": "25",
        "story": "25 monet do 5 słoików po równo. Ile monet w każdym słoiku?",
        "lesson_text": None,
        "explanation": "25 ÷ 5 = 5\nDwadzieścia pięć monet na 5 słoików: po 5 w każdym!",
        "hints": ["5 × 5 = 25, więc 25 ÷ 5 = 5", "Licz po 5: 5, 10, 15, 20, 25"],
    },

    # ══════════════════════════════════════════
    #  POŁĄCZENIE ×÷ (odwrotność)
    # ══════════════════════════════════════════
    {
        "id": 37,
        "title": "🏆 Odkrycie: × i ÷ to przyjaciele!",
        "lesson_type": "challenge",
        "type": "divide",
        "table": 4,
        "a": 12, "b": 4,
        "problem": "12 ÷ 4 = ?",
        "answer": 3,
        "options": [2, 3, 4, 6],
        "visual_type": "split",
        "visual_emoji": "🌺",
        "visual_total": 12,
        "visual_groups": 4,
        "visual_group_label": "Wazon",
        "story": "Wiedziałeś, że 3 × 4 = 12? To znaczy, że 12 ÷ 4 = 3! To działa odwrotnie!",
        "lesson_text": "Mnożenie i dzielenie to odwrotności!\nJeśli 3 × 4 = 12, to 12 ÷ 4 = 3 i 12 ÷ 3 = 4!",
        "explanation": "12 ÷ 4 = 3\nSkoro 3 × 4 = 12, to 12 ÷ 4 = 3. Mnożenie i dzielenie to odwrotności!",
        "hints": ["Jakie 2 liczby pomnożone dają 12?", "3 × 4 = 12, więc 12 ÷ 4 = ?"],
    },
    {
        "id": 38,
        "title": "🏆 Wyzwanie: Rodzina działań",
        "lesson_type": "challenge",
        "type": "divide",
        "table": 5,
        "a": 15, "b": 5,
        "problem": "15 ÷ 5 = ?",
        "answer": 3,
        "options": [2, 3, 4, 5],
        "visual_type": "split",
        "visual_emoji": "🎁",
        "visual_total": 15,
        "visual_groups": 5,
        "visual_group_label": "Dziecko",
        "story": "5 dzieci dostaje po równo 15 prezentów. Ile prezentów dostaje każde dziecko?",
        "lesson_text": "Pamiętaj: 3 × 5 = 15, więc 15 ÷ 5 = 3 i 15 ÷ 3 = 5!",
        "explanation": "15 ÷ 5 = 3\nSkoro 3 × 5 = 15, to 15 ÷ 5 = 3!",
        "hints": ["3 × 5 = 15, więc 15 ÷ 5 = ?"],
    },
    {
        "id": 39,
        "title": "🏆 Zadanie słowne",
        "lesson_type": "challenge",
        "type": "multiply",
        "table": 3,
        "a": 5, "b": 3,
        "problem": "5 × 3 = ?",
        "answer": 15,
        "options": [12, 14, 15, 18],
        "visual_type": "groups",
        "visual_emoji": "🧸",
        "visual_groups": 5,
        "visual_per_group": 3,
        "visual_group_label": "Półka",
        "story": "W sklepie jest 5 półek z misiami. Na każdej półce stoją 3 misie. Ile misków razem sprzedaje sklep?",
        "lesson_text": "Przeczytaj uważnie: ile grup? Ile w każdej grupie? Potem mnóż!",
        "explanation": "5 × 3 = 15\nPięć półek po 3 misie: 3+3+3+3+3 = 15 misiów!",
        "hints": ["Ile półek? Ile misków na półce?", "5 grup po 3: 3, 6, 9, 12, 15"],
    },
    {
        "id": 40,
        "title": "🏆 Wielkie Wyzwanie!",
        "lesson_type": "challenge",
        "type": "divide",
        "table": 4,
        "a": 20, "b": 4,
        "problem": "20 ÷ 4 = ?",
        "answer": 5,
        "options": [4, 5, 6, 10],
        "visual_type": "split",
        "visual_emoji": "🏆",
        "visual_total": 20,
        "visual_groups": 4,
        "visual_group_label": "Drużyna",
        "story": "Na turnieju 20 graczy tworzy 4 równe drużyny. Ilu graczy ma każda drużyna?",
        "lesson_text": "Ostatnie wyzwanie! Przypomnij sobie: × i ÷ to odwrotności. 4 × 5 = 20, więc 20 ÷ 4 = ?",
        "explanation": "20 ÷ 4 = 5\nDwadzieścia graczy na 4 drużyny: po 5 graczy w każdej!",
        "hints": ["4 × 5 = 20, więc 20 ÷ 4 = 5"],
    },

    # ══════════════════════════════════════════
    #  WIĘCEJ ×2  –  większe liczby  (41-43)
    # ══════════════════════════════════════════
    {
        "id": 41,
        "title": "🏃 ×2: Siedem grup",
        "lesson_type": "practice",
        "type": "multiply",
        "table": 2,
        "a": 7, "b": 2,
        "problem": "7 × 2 = ?",
        "answer": 14,
        "options": [12, 13, 14, 16],
        "visual_type": "groups",
        "visual_emoji": "🎵",
        "visual_groups": 7,
        "visual_per_group": 2,
        "visual_group_label": "Duet",
        "story": "Siedem duetów muzycznych – każdy to 2 muzyków. Ile muzyków razem?",
        "lesson_text": "Licz po 2 aż do 7. kroku: 2, 4, 6, 8, 10, 12, 14!",
        "explanation": "7 × 2 = 14\nSiedem duetów po 2 muzyków: 2+2+2+2+2+2+2 = 14!",
        "hints": ["Licz po 2: 2, 4, 6, 8, 10, 12, 14"],
    },
    {
        "id": 42,
        "title": "🧪 ×2: Osiem grup",
        "lesson_type": "test",
        "type": "multiply",
        "table": 2,
        "a": 8, "b": 2,
        "problem": "8 × 2 = ?",
        "answer": 16,
        "options": [14, 15, 16, 18],
        "visual_type": "groups",
        "visual_emoji": "🌸",
        "visual_groups": 8,
        "visual_per_group": 2,
        "visual_group_label": "Para",
        "story": "8 wazonów, w każdym 2 kwiaty. Ile kwiatów razem?",
        "lesson_text": None,
        "explanation": "8 × 2 = 16\nOsiem par kwiatów: 2+2+2+2+2+2+2+2 = 16!",
        "hints": ["Licz po 2 osiem razy: …12, 14, 16"],
    },
    {
        "id": 43,
        "title": "🏆 ×2: Siatka 2 × 9",
        "lesson_type": "challenge",
        "type": "multiply",
        "table": 2,
        "a": 2, "b": 9,
        "problem": "2 × 9 = ?",
        "answer": 18,
        "options": [16, 17, 18, 20],
        "visual_type": "array",
        "visual_emoji": "🦋",
        "visual_rows": 2,
        "visual_cols": 9,
        "story": "Siatka 2 wiersze × 9 kolumn motyli. Ile motyli razem?",
        "lesson_text": "Siatka: 2 wiersze po 9 = 9 + 9 = 18!",
        "explanation": "2 × 9 = 18\nDwa wiersze po 9 motyli: 9 + 9 = 18!",
        "hints": ["Policz wiersz po wierszu: 9, 18"],
    },

    # ══════════════════════════════════════════
    #  WIĘCEJ ×3  –  większe liczby  (44-46)
    # ══════════════════════════════════════════
    {
        "id": 44,
        "title": "🏃 ×3: Sześć grup",
        "lesson_type": "practice",
        "type": "multiply",
        "table": 3,
        "a": 6, "b": 3,
        "problem": "6 × 3 = ?",
        "answer": 18,
        "options": [15, 16, 18, 21],
        "visual_type": "groups",
        "visual_emoji": "🌻",
        "visual_groups": 6,
        "visual_per_group": 3,
        "visual_group_label": "Wiązanka",
        "story": "6 wiązanek słoneczników, w każdej 3 kwiaty. Ile kwiatów razem?",
        "lesson_text": "Licz po 3 sześć razy: 3, 6, 9, 12, 15, 18!",
        "explanation": "6 × 3 = 18\nSześć wiązanek po 3: 3+3+3+3+3+3 = 18!",
        "hints": ["Licz po 3: 3, 6, 9, 12, 15, 18"],
    },
    {
        "id": 45,
        "title": "🧪 ×3: Siatka 3 × 7",
        "lesson_type": "test",
        "type": "multiply",
        "table": 3,
        "a": 3, "b": 7,
        "problem": "3 × 7 = ?",
        "answer": 21,
        "options": [18, 20, 21, 24],
        "visual_type": "array",
        "visual_emoji": "🔮",
        "visual_rows": 3,
        "visual_cols": 7,
        "story": "Siatka kryształowych kul: 3 wiersze po 7. Ile kul razem?",
        "lesson_text": None,
        "explanation": "3 × 7 = 21\nTrzy wiersze po 7 kul: 7+7+7 = 21!",
        "hints": ["Policz wiersz po wierszu: 7, 14, 21"],
    },
    {
        "id": 46,
        "title": "🏆 ×3: Siatka 3 × 8",
        "lesson_type": "challenge",
        "type": "multiply",
        "table": 3,
        "a": 3, "b": 8,
        "problem": "3 × 8 = ?",
        "answer": 24,
        "options": [21, 22, 24, 27],
        "visual_type": "array",
        "visual_emoji": "🌙",
        "visual_rows": 3,
        "visual_cols": 8,
        "story": "Księżyce w grze: 3 wiersze po 8. Ile księżyców razem?",
        "lesson_text": "Policz każdy wiersz osobno, a potem dodaj: 8, 16, 24!",
        "explanation": "3 × 8 = 24\nTrzy wiersze po 8: 8+8+8 = 24!",
        "hints": ["Policz wiersz po wierszu: 8, 16, 24"],
    },

    # ══════════════════════════════════════════
    #  WIĘCEJ ×4  –  większe liczby  (47-49)
    # ══════════════════════════════════════════
    {
        "id": 47,
        "title": "🏃 ×4: Siatka 4 × 6",
        "lesson_type": "practice",
        "type": "multiply",
        "table": 4,
        "a": 4, "b": 6,
        "problem": "4 × 6 = ?",
        "answer": 24,
        "options": [20, 22, 24, 28],
        "visual_type": "array",
        "visual_emoji": "🍊",
        "visual_rows": 4,
        "visual_cols": 6,
        "story": "Skrzynka pomarańczy: 4 wiersze po 6 owoców. Ile pomarańczy razem?",
        "lesson_text": "Policz wiersz po wierszu: 6, 12, 18, 24!",
        "explanation": "4 × 6 = 24\nCztery wiersze po 6 pomarańczy: 6+6+6+6 = 24!",
        "hints": ["Licz po 6: 6, 12, 18, 24"],
    },
    {
        "id": 48,
        "title": "🧪 ×4: Skoki po 4",
        "lesson_type": "test",
        "type": "multiply",
        "table": 4,
        "a": 7, "b": 4,
        "problem": "7 × 4 = ?",
        "answer": 28,
        "options": [24, 26, 28, 32],
        "visual_type": "number_line",
        "visual_jump": 4,
        "visual_jumps": 7,
        "visual_end": 28,
        "story": "Żaba skacze po 4 liście naraz. Po 7 skokach – gdzie jest żaba?",
        "lesson_text": None,
        "explanation": "7 × 4 = 28\nSiedem skoków po 4: 4+4+4+4+4+4+4 = 28!",
        "hints": ["Licz po 4: 4, 8, 12, 16, 20, 24, 28"],
    },
    {
        "id": 49,
        "title": "🏆 ×4: Osiem skoków",
        "lesson_type": "challenge",
        "type": "multiply",
        "table": 4,
        "a": 8, "b": 4,
        "problem": "8 × 4 = ?",
        "answer": 32,
        "options": [28, 30, 32, 36],
        "visual_type": "number_line",
        "visual_jump": 4,
        "visual_jumps": 8,
        "visual_end": 32,
        "story": "Robot robi 8 kroków po 4 metry. Ile metrów przeszedł razem?",
        "lesson_text": "To wyzwanie! Licz po 4 osiem razy: …24, 28, 32!",
        "explanation": "8 × 4 = 32\nOsiem kroków po 4 metry: 4×8 = 32!",
        "hints": ["Licz po 4: 4, 8, 12, 16, 20, 24, 28, 32"],
    },

    # ══════════════════════════════════════════
    #  WIĘCEJ ×5  –  większe liczby  (50-52)
    # ══════════════════════════════════════════
    {
        "id": 50,
        "title": "🏃 ×5: Skoki po 5",
        "lesson_type": "practice",
        "type": "multiply",
        "table": 5,
        "a": 6, "b": 5,
        "problem": "6 × 5 = ?",
        "answer": 30,
        "options": [25, 28, 30, 35],
        "visual_type": "number_line",
        "visual_jump": 5,
        "visual_jumps": 6,
        "visual_end": 30,
        "story": "Kangur robi 6 skoków po 5 metrów. Ile metrów skoczył?",
        "lesson_text": "Licz po 5 sześć razy: 5, 10, 15, 20, 25, 30!",
        "explanation": "6 × 5 = 30\nSześć skoków po 5 metrów: 5×6 = 30!",
        "hints": ["Licz po 5: 5, 10, 15, 20, 25, 30"],
    },
    {
        "id": 51,
        "title": "🧪 ×5: Siedem skoków",
        "lesson_type": "test",
        "type": "multiply",
        "table": 5,
        "a": 7, "b": 5,
        "problem": "7 × 5 = ?",
        "answer": 35,
        "options": [30, 33, 35, 40],
        "visual_type": "number_line",
        "visual_jump": 5,
        "visual_jumps": 7,
        "visual_end": 35,
        "story": "7 słoiczków miodu po 5 łyżeczek każdy. Ile łyżeczek razem?",
        "lesson_text": None,
        "explanation": "7 × 5 = 35\nSiedem słoiczków po 5: 5+5+5+5+5+5+5 = 35!",
        "hints": ["Licz po 5: …25, 30, 35"],
    },
    {
        "id": 52,
        "title": "🏆 ×5: Osiem skoków",
        "lesson_type": "challenge",
        "type": "multiply",
        "table": 5,
        "a": 8, "b": 5,
        "problem": "8 × 5 = ?",
        "answer": 40,
        "options": [35, 38, 40, 45],
        "visual_type": "number_line",
        "visual_jump": 5,
        "visual_jumps": 8,
        "visual_end": 40,
        "story": "8 worków z 5 marchewkami w każdym. Ile marchewek razem?",
        "lesson_text": "Ostatni krok ×5! Licz po 5 osiem razy: …35, 40!",
        "explanation": "8 × 5 = 40\nOsiem worków po 5 marchewek: 5×8 = 40!",
        "hints": ["Licz po 5: …30, 35, 40"],
    },

    # ══════════════════════════════════════════
    #  WIĘCEJ ÷2  –  większe liczby  (53-55)
    # ══════════════════════════════════════════
    {
        "id": 53,
        "title": "🏃 ÷2: Czternaście na dwie grupy",
        "lesson_type": "practice",
        "type": "divide",
        "table": 2,
        "a": 14, "b": 2,
        "problem": "14 ÷ 2 = ?",
        "answer": 7,
        "options": [5, 6, 7, 8],
        "visual_type": "split",
        "visual_emoji": "🎀",
        "visual_total": 14,
        "visual_groups": 2,
        "visual_group_label": "Koszyk",
        "story": "14 kokardek podzielono na 2 koszyki po równo. Ile kokardek w każdym?",
        "lesson_text": "Połowa z 14 to 7! 7 + 7 = 14.",
        "explanation": "14 ÷ 2 = 7\nCzternaście kokardek na 2 koszyki: po 7 w każdym!",
        "hints": ["Połowa z 14 to ?", "7 + 7 = 14"],
    },
    {
        "id": 54,
        "title": "🧪 ÷2: Osiemnaście na dwie grupy",
        "lesson_type": "test",
        "type": "divide",
        "table": 2,
        "a": 18, "b": 2,
        "problem": "18 ÷ 2 = ?",
        "answer": 9,
        "options": [7, 8, 9, 10],
        "visual_type": "split",
        "visual_emoji": "🍑",
        "visual_total": 18,
        "visual_groups": 2,
        "visual_group_label": "Talerz",
        "story": "18 brzoskwiń na 2 talerze po równo. Ile brzoskwiń na każdym?",
        "lesson_text": None,
        "explanation": "18 ÷ 2 = 9\nOsemnaście brzoskwiń na 2 talerze: po 9 na każdym!",
        "hints": ["9 + 9 = 18, więc 18 ÷ 2 = 9"],
    },
    {
        "id": 55,
        "title": "🏆 ÷2: Dwadzieścia na dwie grupy",
        "lesson_type": "challenge",
        "type": "divide",
        "table": 2,
        "a": 20, "b": 2,
        "problem": "20 ÷ 2 = ?",
        "answer": 10,
        "options": [8, 9, 10, 11],
        "visual_type": "split",
        "visual_emoji": "🪷",
        "visual_total": 20,
        "visual_groups": 2,
        "visual_group_label": "Wazon",
        "story": "20 tulipanów do 2 wazonów po równo. Ile kwiatów w każdym wazonie?",
        "lesson_text": "Połowa z 20 to 10! 10 + 10 = 20.",
        "explanation": "20 ÷ 2 = 10\nDwadzieścia tulipanów na 2 wazony: po 10 w każdym!",
        "hints": ["10 + 10 = 20, więc 20 ÷ 2 = 10"],
    },

    # ══════════════════════════════════════════
    #  WIĘCEJ ÷3  –  większe liczby  (56-58)
    # ══════════════════════════════════════════
    {
        "id": 56,
        "title": "🏃 ÷3: Osiemnaście na trzy grupy",
        "lesson_type": "practice",
        "type": "divide",
        "table": 3,
        "a": 18, "b": 3,
        "problem": "18 ÷ 3 = ?",
        "answer": 6,
        "options": [4, 5, 6, 7],
        "visual_type": "split",
        "visual_emoji": "🌷",
        "visual_total": 18,
        "visual_groups": 3,
        "visual_group_label": "Doniczka",
        "story": "18 tulipanów do 3 doniczek po równo. Ile kwiatów w każdej?",
        "lesson_text": "3 × 6 = 18, więc 18 ÷ 3 = 6!",
        "explanation": "18 ÷ 3 = 6\nOsemnaście tulipanów na 3 doniczki: po 6 w każdej!",
        "hints": ["3 × 6 = 18, więc 18 ÷ 3 = 6"],
    },
    {
        "id": 57,
        "title": "🧪 ÷3: Dwadzieścia jeden na trzy grupy",
        "lesson_type": "test",
        "type": "divide",
        "table": 3,
        "a": 21, "b": 3,
        "problem": "21 ÷ 3 = ?",
        "answer": 7,
        "options": [6, 7, 8, 9],
        "visual_type": "split",
        "visual_emoji": "🎊",
        "visual_total": 21,
        "visual_groups": 3,
        "visual_group_label": "Worek",
        "story": "21 balonów do 3 worków po równo. Ile balonów w każdym worku?",
        "lesson_text": None,
        "explanation": "21 ÷ 3 = 7\nDwadzieścia jeden balonów na 3 worki: po 7 w każdym!",
        "hints": ["3 × 7 = 21, więc 21 ÷ 3 = 7"],
    },
    {
        "id": 58,
        "title": "🏆 ÷3: Dwadzieścia cztery na trzy grupy",
        "lesson_type": "challenge",
        "type": "divide",
        "table": 3,
        "a": 24, "b": 3,
        "problem": "24 ÷ 3 = ?",
        "answer": 8,
        "options": [6, 7, 8, 9],
        "visual_type": "split",
        "visual_emoji": "🎉",
        "visual_total": 24,
        "visual_groups": 3,
        "visual_group_label": "Pudełko",
        "story": "24 fajerwerki do 3 pudełek po równo. Ile w każdym pudełku?",
        "lesson_text": "3 × 8 = 24, więc 24 ÷ 3 = 8!",
        "explanation": "24 ÷ 3 = 8\nDwadzieścia cztery fajerwerki na 3 pudełka: po 8 w każdym!",
        "hints": ["3 × 8 = 24, więc 24 ÷ 3 = 8"],
    },

    # ══════════════════════════════════════════
    #  WIĘCEJ ÷4  –  większe liczby  (59-61)
    # ══════════════════════════════════════════
    {
        "id": 59,
        "title": "🏃 ÷4: Dwadzieścia cztery na cztery grupy",
        "lesson_type": "practice",
        "type": "divide",
        "table": 4,
        "a": 24, "b": 4,
        "problem": "24 ÷ 4 = ?",
        "answer": 6,
        "options": [4, 5, 6, 8],
        "visual_type": "split",
        "visual_emoji": "🦜",
        "visual_total": 24,
        "visual_groups": 4,
        "visual_group_label": "Klatka",
        "story": "24 papugi do 4 klatek po równo. Ile papug w każdej klatce?",
        "lesson_text": "4 × 6 = 24, więc 24 ÷ 4 = 6!",
        "explanation": "24 ÷ 4 = 6\nDwadzieścia cztery papugi na 4 klatki: po 6 w każdej!",
        "hints": ["4 × 6 = 24, więc 24 ÷ 4 = 6"],
    },
    {
        "id": 60,
        "title": "🧪 ÷4: Skoki po 4 (28 ÷ 4)",
        "lesson_type": "test",
        "type": "divide",
        "table": 4,
        "a": 28, "b": 4,
        "problem": "28 ÷ 4 = ?",
        "answer": 7,
        "options": [5, 6, 7, 8],
        "visual_type": "number_line",
        "visual_jump": 4,
        "visual_jumps": 7,
        "visual_end": 28,
        "story": "Ile skoków po 4 trzeba, żeby dojść do 28?",
        "lesson_text": None,
        "explanation": "28 ÷ 4 = 7\nSiedem skoków po 4: 4+4+4+4+4+4+4 = 28!",
        "hints": ["Licz skoki po 4: 4, 8, 12, 16, 20, 24, 28 – ile skoków?"],
    },
    {
        "id": 61,
        "title": "🏆 ÷4: Skoki po 4 (32 ÷ 4)",
        "lesson_type": "challenge",
        "type": "divide",
        "table": 4,
        "a": 32, "b": 4,
        "problem": "32 ÷ 4 = ?",
        "answer": 8,
        "options": [6, 7, 8, 9],
        "visual_type": "number_line",
        "visual_jump": 4,
        "visual_jumps": 8,
        "visual_end": 32,
        "story": "Ile skoków po 4 metry potrzeba, żeby przejść 32 metry?",
        "lesson_text": "4 × 8 = 32, więc 32 ÷ 4 = 8! Policz skoki na osi!",
        "explanation": "32 ÷ 4 = 8\nOsiem skoków po 4: 4×8 = 32!",
        "hints": ["4 × 8 = 32, więc 32 ÷ 4 = 8"],
    },

    # ══════════════════════════════════════════
    #  WIĘCEJ ÷5  –  większe liczby  (62-64)
    # ══════════════════════════════════════════
    {
        "id": 62,
        "title": "🏃 ÷5: Skoki po 5 (30 ÷ 5)",
        "lesson_type": "practice",
        "type": "divide",
        "table": 5,
        "a": 30, "b": 5,
        "problem": "30 ÷ 5 = ?",
        "answer": 6,
        "options": [5, 6, 7, 8],
        "visual_type": "number_line",
        "visual_jump": 5,
        "visual_jumps": 6,
        "visual_end": 30,
        "story": "Ile skoków po 5 potrzeba, żeby dojść do 30?",
        "lesson_text": "5 × 6 = 30, więc 30 ÷ 5 = 6! Policz skoki!",
        "explanation": "30 ÷ 5 = 6\nSześć skoków po 5: 5+5+5+5+5+5 = 30!",
        "hints": ["Licz po 5: 5, 10, 15, 20, 25, 30 – ile skoków?"],
    },
    {
        "id": 63,
        "title": "🧪 ÷5: Skoki po 5 (35 ÷ 5)",
        "lesson_type": "test",
        "type": "divide",
        "table": 5,
        "a": 35, "b": 5,
        "problem": "35 ÷ 5 = ?",
        "answer": 7,
        "options": [6, 7, 8, 9],
        "visual_type": "number_line",
        "visual_jump": 5,
        "visual_jumps": 7,
        "visual_end": 35,
        "story": "Ile skoków po 5 potrzeba, żeby dojść do 35?",
        "lesson_text": None,
        "explanation": "35 ÷ 5 = 7\nSiedem skoków po 5: 5×7 = 35!",
        "hints": ["5 × 7 = 35, więc 35 ÷ 5 = 7"],
    },
    {
        "id": 64,
        "title": "🏆 ÷5: Skoki po 5 (40 ÷ 5)",
        "lesson_type": "challenge",
        "type": "divide",
        "table": 5,
        "a": 40, "b": 5,
        "problem": "40 ÷ 5 = ?",
        "answer": 8,
        "options": [6, 7, 8, 10],
        "visual_type": "number_line",
        "visual_jump": 5,
        "visual_jumps": 8,
        "visual_end": 40,
        "story": "Ile skoków po 5 potrzeba, żeby dojść do 40?",
        "lesson_text": "5 × 8 = 40, więc 40 ÷ 5 = 8! Super wyzwanie!",
        "explanation": "40 ÷ 5 = 8\nOsiem skoków po 5: 5×8 = 40!",
        "hints": ["5 × 8 = 40, więc 40 ÷ 5 = 8"],
    },

    # ══════════════════════════════════════════
    #  TABELA ×6  –  nowa tabela!  (65-68)
    # ══════════════════════════════════════════
    {
        "id": 65,
        "title": "📖 Nowa tabela: ×6",
        "lesson_type": "lesson",
        "type": "multiply",
        "table": 6,
        "a": 2, "b": 6,
        "problem": "2 × 6 = ?",
        "answer": 12,
        "options": [10, 11, 12, 14],
        "visual_type": "groups",
        "visual_emoji": "🍋",
        "visual_groups": 2,
        "visual_per_group": 6,
        "visual_group_label": "Koszyk",
        "story": "2 koszyki po 6 cytryn. Ile cytryn razem?",
        "lesson_text": "Nowa tabela: ×6! 2 × 6 = 2 grupy po 6 = 6 + 6 = 12.",
        "explanation": "2 × 6 = 12\nDwa koszyki po 6 cytryn: 6 + 6 = 12!",
        "hints": ["6 + 6 = 12"],
    },
    {
        "id": 66,
        "title": "📖 ×6: Trzy grupy",
        "lesson_type": "lesson",
        "type": "multiply",
        "table": 6,
        "a": 3, "b": 6,
        "problem": "3 × 6 = ?",
        "answer": 18,
        "options": [15, 16, 18, 21],
        "visual_type": "groups",
        "visual_emoji": "🍏",
        "visual_groups": 3,
        "visual_per_group": 6,
        "visual_group_label": "Skrzynka",
        "story": "3 skrzynki jabłek, w każdej 6 owoców. Ile jabłek razem?",
        "lesson_text": "Licz po 6: 6 → 12 → 18. Trzy kroki po 6!",
        "explanation": "3 × 6 = 18\nTrzy skrzynki po 6 jabłek: 6+6+6 = 18!",
        "hints": ["Licz po 6: 6, 12, 18"],
    },
    {
        "id": 67,
        "title": "🏃 ×6: Siatka 4 × 6",
        "lesson_type": "practice",
        "type": "multiply",
        "table": 6,
        "a": 4, "b": 6,
        "problem": "4 × 6 = ?",
        "answer": 24,
        "options": [20, 22, 24, 28],
        "visual_type": "array",
        "visual_emoji": "🍇",
        "visual_rows": 4,
        "visual_cols": 6,
        "story": "Siatka winogron: 4 wiersze po 6 gronek. Ile gronek razem?",
        "lesson_text": "Licz wiersz po wierszu: 6, 12, 18, 24!",
        "explanation": "4 × 6 = 24\nCztery wiersze po 6 gronek: 6+6+6+6 = 24!",
        "hints": ["Licz po 6: 6, 12, 18, 24"],
    },
    {
        "id": 68,
        "title": "🧪 ×6: Skoki po 6",
        "lesson_type": "test",
        "type": "multiply",
        "table": 6,
        "a": 5, "b": 6,
        "problem": "5 × 6 = ?",
        "answer": 30,
        "options": [24, 28, 30, 36],
        "visual_type": "number_line",
        "visual_jump": 6,
        "visual_jumps": 5,
        "visual_end": 30,
        "story": "5 tygodni po 6 dni nauki. Ile dni nauki razem?",
        "lesson_text": None,
        "explanation": "5 × 6 = 30\nPięć tygodni po 6 dni: 6+6+6+6+6 = 30!",
        "hints": ["Licz po 6: 6, 12, 18, 24, 30"],
    },

    # ══════════════════════════════════════════
    #  TABELA ÷6  (69-72)
    # ══════════════════════════════════════════
    {
        "id": 69,
        "title": "📖 Dzielenie przez 6",
        "lesson_type": "lesson",
        "type": "divide",
        "table": 6,
        "a": 12, "b": 6,
        "problem": "12 ÷ 6 = ?",
        "answer": 2,
        "options": [1, 2, 3, 4],
        "visual_type": "split",
        "visual_emoji": "🦊",
        "visual_total": 12,
        "visual_groups": 6,
        "visual_group_label": "Lisek",
        "story": "12 jagód do 6 lisków po równo. Ile jagód dostaje każdy lisek?",
        "lesson_text": "12 ÷ 6 = 2. Skoro 2 × 6 = 12, to 12 ÷ 6 = 2!",
        "explanation": "12 ÷ 6 = 2\nDwanaście jagód na 6 lisków: po 2 dla każdego!",
        "hints": ["2 × 6 = 12, więc 12 ÷ 6 = 2"],
    },
    {
        "id": 70,
        "title": "📖 ÷6: Osiemnaście",
        "lesson_type": "lesson",
        "type": "divide",
        "table": 6,
        "a": 18, "b": 6,
        "problem": "18 ÷ 6 = ?",
        "answer": 3,
        "options": [2, 3, 4, 6],
        "visual_type": "split",
        "visual_emoji": "🦝",
        "visual_total": 18,
        "visual_groups": 6,
        "visual_group_label": "Szop",
        "story": "18 orzechów na 6 szopów po równo. Ile orzechów dostaje każdy szop?",
        "lesson_text": "3 × 6 = 18, więc 18 ÷ 6 = 3!",
        "explanation": "18 ÷ 6 = 3\nOsemnaście orzechów na 6 szopów: po 3 dla każdego!",
        "hints": ["3 × 6 = 18, więc 18 ÷ 6 = 3"],
    },
    {
        "id": 71,
        "title": "🏃 ÷6: Dwadzieścia cztery",
        "lesson_type": "practice",
        "type": "divide",
        "table": 6,
        "a": 24, "b": 6,
        "problem": "24 ÷ 6 = ?",
        "answer": 4,
        "options": [3, 4, 5, 6],
        "visual_type": "split",
        "visual_emoji": "🦡",
        "visual_total": 24,
        "visual_groups": 6,
        "visual_group_label": "Borsuk",
        "story": "24 jagody na 6 borsuków po równo. Ile jagód dostaje każdy?",
        "lesson_text": "4 × 6 = 24, więc 24 ÷ 6 = 4!",
        "explanation": "24 ÷ 6 = 4\nDwadzieścia cztery jagody na 6 borsuków: po 4 dla każdego!",
        "hints": ["4 × 6 = 24, więc 24 ÷ 6 = 4"],
    },
    {
        "id": 72,
        "title": "🧪 ÷6: Trzydzieści",
        "lesson_type": "test",
        "type": "divide",
        "table": 6,
        "a": 30, "b": 6,
        "problem": "30 ÷ 6 = ?",
        "answer": 5,
        "options": [4, 5, 6, 8],
        "visual_type": "number_line",
        "visual_jump": 6,
        "visual_jumps": 5,
        "visual_end": 30,
        "story": "Ile grup po 6 mieści się w 30?",
        "lesson_text": None,
        "explanation": "30 ÷ 6 = 5\nPięć skoków po 6: 6+6+6+6+6 = 30!",
        "hints": ["5 × 6 = 30, więc 30 ÷ 6 = 5"],
    },

    # ══════════════════════════════════════════
    #  NOWA TABELA ×7  (73-75)
    # ══════════════════════════════════════════
    {
        "id": 73,
        "title": "📖 Nowa tabela: ×7",
        "lesson_type": "lesson",
        "type": "multiply",
        "table": 7,
        "a": 2, "b": 7,
        "problem": "2 × 7 = ?",
        "answer": 14,
        "options": [12, 13, 14, 16],
        "visual_type": "groups",
        "visual_emoji": "🌺",
        "visual_groups": 2,
        "visual_per_group": 7,
        "visual_group_label": "Bukiet",
        "story": "2 bukiety po 7 kwiatów. Ile kwiatów razem?",
        "lesson_text": "Tabela ×7! 2 × 7 = 7 + 7 = 14. Tydzień ma 7 dni!",
        "explanation": "2 × 7 = 14\nDwa bukiety po 7 kwiatów: 7 + 7 = 14!",
        "hints": ["7 + 7 = 14"],
    },
    {
        "id": 74,
        "title": "📖 ×7: Trzy tygodnie",
        "lesson_type": "lesson",
        "type": "multiply",
        "table": 7,
        "a": 3, "b": 7,
        "problem": "3 × 7 = ?",
        "answer": 21,
        "options": [18, 19, 21, 24],
        "visual_type": "array",
        "visual_emoji": "🌹",
        "visual_rows": 3,
        "visual_cols": 7,
        "story": "3 tygodnie po 7 dni. Ile dni razem?",
        "lesson_text": "Tydzień = 7 dni! 3 tygodnie = 3 × 7 = 7 + 7 + 7 = 21 dni.",
        "explanation": "3 × 7 = 21\nTrzy tygodnie po 7 dni: 7+7+7 = 21!",
        "hints": ["Tydzień ma 7 dni. 3 tygodnie = 3 × 7"],
    },
    {
        "id": 75,
        "title": "🏃 ×7: Skoki po 7",
        "lesson_type": "practice",
        "type": "multiply",
        "table": 7,
        "a": 4, "b": 7,
        "problem": "4 × 7 = ?",
        "answer": 28,
        "options": [24, 26, 28, 32],
        "visual_type": "number_line",
        "visual_jump": 7,
        "visual_jumps": 4,
        "visual_end": 28,
        "story": "4 tygodnie po 7 dni. Ile dni w 4 tygodniach?",
        "lesson_text": "Licz po 7: 7, 14, 21, 28. Cztery tygodnie!",
        "explanation": "4 × 7 = 28\nCztery tygodnie po 7 dni: 7+7+7+7 = 28!",
        "hints": ["Licz po 7: 7, 14, 21, 28"],
    },

    # ══════════════════════════════════════════
    #  SPECJALNE: ×1 i ×0  (76-77)
    # ══════════════════════════════════════════
    {
        "id": 76,
        "title": "📖 Magiczne: ×1",
        "lesson_type": "lesson",
        "type": "multiply",
        "table": 1,
        "a": 5, "b": 1,
        "problem": "5 × 1 = ?",
        "answer": 5,
        "options": [1, 4, 5, 6],
        "visual_type": "groups",
        "visual_emoji": "⭐",
        "visual_groups": 5,
        "visual_per_group": 1,
        "visual_group_label": "Gwiazdka",
        "story": "5 gwiazdek, każda jest 1. Ile gwiazdek razem?",
        "lesson_text": "Każda liczba pomnożona przez 1 daje siebie samą! 5 × 1 = 5, 9 × 1 = 9, 100 × 1 = 100!",
        "explanation": "5 × 1 = 5\nPięć grup po 1: 1+1+1+1+1 = 5. Liczba × 1 = ta sama liczba!",
        "hints": ["Każda liczba × 1 = ona sama!"],
    },
    {
        "id": 77,
        "title": "📖 Magiczne: ×0",
        "lesson_type": "lesson",
        "type": "multiply",
        "table": 0,
        "a": 4, "b": 0,
        "problem": "4 × 0 = ?",
        "answer": 0,
        "options": [0, 4, 8, 40],
        "visual_type": "groups",
        "visual_emoji": "❓",
        "visual_groups": 4,
        "visual_per_group": 0,
        "visual_group_label": "Puste pudełko",
        "story": "4 pudełka, ale każde pudełko jest PUSTE. Ile przedmiotów razem?",
        "lesson_text": "Każda liczba pomnożona przez 0 daje ZERO! 4 puste pudełka to nadal nic: 4 × 0 = 0.",
        "explanation": "4 × 0 = 0\nCztery puste pudełka: 0+0+0+0 = 0. Liczba × 0 zawsze = 0!",
        "hints": ["Puste pudełko = 0 przedmiotów", "Cokolwiek × 0 = 0!"],
    },

    # ══════════════════════════════════════════
    #  BRAKUJĄCE LICZBY  (78-80)
    # ══════════════════════════════════════════
    {
        "id": 78,
        "title": "🔍 Brakująca liczba: ? × 4 = 20",
        "lesson_type": "challenge",
        "type": "multiply",
        "table": 4,
        "a": 5, "b": 4,
        "problem": "? × 4 = 20",
        "answer": 5,
        "options": [3, 4, 5, 6],
        "visual_type": "groups",
        "visual_emoji": "🔍",
        "visual_groups": 5,
        "visual_per_group": 4,
        "visual_group_label": "Grupa",
        "story": "Ile grup po 4 daje w sumie 20? Znajdź brakującą liczbę!",
        "lesson_text": "Szukamy ?: ? × 4 = 20. Policz grupy po 4: 4, 8, 12, 16, 20 – to 5 grup!",
        "explanation": "5 × 4 = 20\nPięć grup po 4 daje 20! Brakująca liczba to 5.",
        "hints": ["Licz po 4: ile kroków do 20?", "4, 8, 12, 16, 20 – ile kroków?"],
    },
    {
        "id": 79,
        "title": "🔍 Brakująca liczba: 24 ÷ ? = 6",
        "lesson_type": "challenge",
        "type": "divide",
        "table": 4,
        "a": 24, "b": 4,
        "problem": "24 ÷ ? = 6",
        "answer": 4,
        "options": [3, 4, 5, 6],
        "visual_type": "split",
        "visual_emoji": "🔮",
        "visual_total": 24,
        "visual_groups": 4,
        "visual_group_label": "Grupa",
        "story": "24 kryształy podzielono tak, że w każdej grupie jest 6. Na ile grup podzielono?",
        "lesson_text": "Szukamy ?: 24 ÷ ? = 6. Oznacza to: ile grup po 6 mieści się w 24? 6, 12, 18, 24 – to 4 grupy!",
        "explanation": "24 ÷ 4 = 6\nBrakująca liczba to 4. Dwadzieścia cztery na 4 grupy daje po 6!",
        "hints": ["Ile grup po 6 mieści się w 24?", "6 × ? = 24"],
    },
    {
        "id": 80,
        "title": "🏆 Wielkie Wyzwanie Finałowe!",
        "lesson_type": "challenge",
        "type": "multiply",
        "table": 5,
        "a": 7, "b": 5,
        "problem": "? × 5 = 35",
        "answer": 7,
        "options": [5, 6, 7, 8],
        "visual_type": "number_line",
        "visual_jump": 5,
        "visual_jumps": 7,
        "visual_end": 35,
        "story": "Ile tygodni po 5 dni szkoły składa się na 35 dni? Znajdź brakującą liczbę!",
        "lesson_text": "Ostatnie wyzwanie! Licz po 5 na osi: 5, 10, 15, 20, 25, 30, 35 – ile skoków?",
        "explanation": "7 × 5 = 35\nBrakująca liczba to 7. Siedem tygodni po 5 dni szkoły = 35 dni!",
        "hints": ["Licz po 5: 5, 10, 15, 20, 25, 30, 35 – ile kroków?", "7 × 5 = 35"],
    },
]
