"""KidCoder – Memory card matching game data."""

MEMORY_PAIRS = [
    {
        "id": 1,
        "title": "Podstawy programowania",
        "description": "Dopasuj emoji do pojęcia!",
        "pairs": [
            {"emoji": "📦", "name": "Zmienna"},
            {"emoji": "🔄", "name": "Pętla"},
            {"emoji": "❓", "name": "Warunek IF"},
            {"emoji": "📝", "name": "Funkcja"},
        ],
        "time_limit": 60,
        "hints": ["Zmienna to jak pudełko na dane", "Pętla się kręci w kółko"],
    },
    {
        "id": 2,
        "title": "Typy danych",
        "description": "Dopasuj typ danych do ikony!",
        "pairs": [
            {"emoji": "🔢", "name": "Liczba"},
            {"emoji": "📜", "name": "Tekst"},
            {"emoji": "✅", "name": "Prawda/Fałsz"},
            {"emoji": "📋", "name": "Lista"},
        ],
        "time_limit": 60,
        "hints": ["Liczby zapisujemy cyframi", "Tekst to słowa i zdania"],
    },
    {
        "id": 3,
        "title": "Narzędzia programisty",
        "description": "Co robi programista?",
        "pairs": [
            {"emoji": "🐛", "name": "Bug (błąd)"},
            {"emoji": "🔍", "name": "Debugowanie"},
            {"emoji": "💾", "name": "Zapisywanie"},
            {"emoji": "▶️", "name": "Uruchamianie"},
            {"emoji": "🧪", "name": "Testowanie"},
        ],
        "time_limit": 75,
        "hints": ["Bug to robak – błąd w kodzie", "Debug to szukanie błędów"],
    },
    {
        "id": 4,
        "title": "Elementy kodu",
        "description": "Połącz symbole z pojęciami!",
        "pairs": [
            {"emoji": "{ }", "name": "Blok kodu"},
            {"emoji": "( )", "name": "Nawiasy"},
            {"emoji": "[ ]", "name": "Tablica"},
            {"emoji": "# ", "name": "Komentarz"},
            {"emoji": "=", "name": "Przypisanie"},
        ],
        "time_limit": 75,
        "hints": ["Klamry otaczają blok kodu", "Hash oznacza komentarz"],
    },
    {
        "id": 5,
        "title": "Akcje w kodzie",
        "description": "Co robią te polecenia?",
        "pairs": [
            {"emoji": "🖨️", "name": "print()"},
            {"emoji": "📥", "name": "input()"},
            {"emoji": "📏", "name": "len()"},
            {"emoji": "🔀", "name": "sort()"},
            {"emoji": "➕", "name": "append()"},
        ],
        "time_limit": 75,
        "hints": ["print drukuje tekst na ekranie", "input pobiera dane od użytkownika"],
    },
    {
        "id": 6,
        "title": "Bohaterowie IT",
        "description": "Dopasuj postać do opisu!",
        "pairs": [
            {"emoji": "🤖", "name": "Robot"},
            {"emoji": "🌐", "name": "Internet"},
            {"emoji": "💻", "name": "Komputer"},
            {"emoji": "📱", "name": "Aplikacja"},
            {"emoji": "🔒", "name": "Hasło"},
            {"emoji": "☁️", "name": "Chmura"},
        ],
        "time_limit": 90,
        "hints": ["Robot wykonuje polecenia", "Chmura przechowuje pliki online"],
    },
    {
        "id": 7,
        "title": "Struktury sterujące",
        "description": "Jak sterujemy programem?",
        "pairs": [
            {"emoji": "🔁", "name": "Pętla FOR"},
            {"emoji": "⏳", "name": "Pętla WHILE"},
            {"emoji": "🔀", "name": "IF / ELSE"},
            {"emoji": "🎯", "name": "RETURN"},
            {"emoji": "⏹️", "name": "BREAK"},
            {"emoji": "⏭️", "name": "CONTINUE"},
        ],
        "time_limit": 90,
        "hints": ["FOR powtarza określoną liczbę razy", "WHILE powtarza dopóki warunek jest prawdziwy"],
    },
    {
        "id": 8,
        "title": "Algorytmy",
        "description": "Dopasuj algorytm do ikony!",
        "pairs": [
            {"emoji": "🔍", "name": "Wyszukiwanie"},
            {"emoji": "📊", "name": "Sortowanie"},
            {"emoji": "🌳", "name": "Drzewo"},
            {"emoji": "🗺️", "name": "Mapa (słownik)"},
            {"emoji": "📚", "name": "Stos"},
            {"emoji": "🚶", "name": "Kolejka"},
        ],
        "time_limit": 90,
        "hints": ["Stos – ostatni wchodzi, pierwszy wychodzi", "Kolejka – pierwszy wchodzi, pierwszy wychodzi"],
    },
    {
        "id": 9,
        "title": "Języki programowania",
        "description": "Rozpoznaj języki programowania!",
        "pairs": [
            {"emoji": "🐍", "name": "Python"},
            {"emoji": "☕", "name": "Java"},
            {"emoji": "🌐", "name": "JavaScript"},
            {"emoji": "💎", "name": "Ruby"},
            {"emoji": "🦀", "name": "Rust"},
            {"emoji": "🐹", "name": "Go"},
            {"emoji": "🍎", "name": "Swift"},
        ],
        "time_limit": 120,
        "hints": ["Python ma wężyka w logo", "Java kojarzy się z kawą"],
    },
    {
        "id": 10,
        "title": "Wielki mix!",
        "description": "Wszystko razem – mistrz memory!",
        "pairs": [
            {"emoji": "📦", "name": "Zmienna"},
            {"emoji": "🔄", "name": "Pętla"},
            {"emoji": "🐛", "name": "Bug"},
            {"emoji": "🐍", "name": "Python"},
            {"emoji": "💾", "name": "Zapis"},
            {"emoji": "🔒", "name": "Hasło"},
            {"emoji": "🖨️", "name": "print()"},
            {"emoji": "📊", "name": "Sortowanie"},
        ],
        "time_limit": 120,
        "hints": ["Użyj tego, co wiesz z poprzednich poziomów!"],
    },
]
