"""Pixel art puzzles – child decodes a run-length coded picture (koduj obrazki).

Each puzzle:
  id, title, description  – metadata
  size                    – grid is size x size
  palette                 – letter -> {color, name}; "." means empty cell
  grid                    – list of strings (rows), chars from palette or "."
  hints                   – progressive hints (PL)
"""

PIXEL_PUZZLES = [
    {
        "id": 1,
        "title": "🎨 Serce",
        "description": "Pomaluj serduszko według kodu wiersza!",
        "size": 7,
        "palette": {"R": {"color": "#FF4757", "name": "czerwony"}},
        "grid": [
            ".......",
            ".RR.RR.",
            "RRRRRRR",
            "RRRRRRR",
            ".RRRRR.",
            "..RRR..",
            "...R...",
        ],
        "hints": [
            "Spójrz na kod obok wiersza – mówi ile pól pomalować i na jaki kolor.",
            "Drugi wiersz to: 1 puste, 2 czerwone, 1 puste, 2 czerwone, 1 puste.",
            "Zacznij od środka obrazka – serce jest symetryczne!",
        ],
    },
    {
        "id": 2,
        "title": "👻 Duszek",
        "description": "Zakoduj przyjaznego duszka!",
        "size": 7,
        "palette": {
            "B": {"color": "#54A0FF", "name": "niebieski"},
            "N": {"color": "#2F3542", "name": "czarny"},
        },
        "grid": [
            "..BBB..",
            ".BBBBB.",
            ".BNBNB.",
            ".BBBBB.",
            ".BBBBB.",
            ".BBBBB.",
            ".B.B.B.",
        ],
        "hints": [
            "Duszek ma dwa czarne oczka w trzecim wierszu.",
            "Ostatni wiersz to falbanka: niebieski, puste, niebieski, puste…",
            "Licz pola uważnie – kod zawsze mówi prawdę!",
        ],
    },
    {
        "id": 3,
        "title": "🍄 Grzybek",
        "description": "Muchomorek z kropkami – pomaluj go!",
        "size": 7,
        "palette": {
            "R": {"color": "#FF4757", "name": "czerwony"},
            "Y": {"color": "#FFD93D", "name": "żółty"},
            "K": {"color": "#FFE8C2", "name": "kremowy"},
        },
        "grid": [
            "..RRR..",
            ".RRYRR.",
            "RYRRRYR",
            "RRRRRRR",
            "..KKK..",
            "..KKK..",
            ".KKKKK.",
        ],
        "hints": [
            "Kapelusz jest czerwony z żółtymi kropkami.",
            "Nóżka grzybka jest kremowa i zaczyna się w piątym wierszu.",
            "W trzecim wierszu żółte kropki są na drugim i szóstym polu.",
        ],
    },
    {
        "id": 4,
        "title": "🌸 Kwiatek",
        "description": "Różowy kwiatek na zielonej łodydze.",
        "size": 7,
        "palette": {
            "P": {"color": "#FD79A8", "name": "różowy"},
            "Y": {"color": "#FFD93D", "name": "żółty"},
            "G": {"color": "#2ED573", "name": "zielony"},
        },
        "grid": [
            "..PPP..",
            ".PYYYP.",
            ".PYYYP.",
            "..PPP..",
            "...G...",
            "...GG..",
            "...G...",
        ],
        "hints": [
            "Środek kwiatka jest żółty, płatki różowe.",
            "Łodyga to jedno zielone pole w środku wiersza.",
            "W szóstym wierszu łodyga ma mały listek z prawej strony.",
        ],
    },
    {
        "id": 5,
        "title": "🚀 Rakieta",
        "description": "Rakieta gotowa do startu – 3… 2… 1…!",
        "size": 8,
        "palette": {
            "R": {"color": "#FF4757", "name": "czerwony"},
            "B": {"color": "#54A0FF", "name": "niebieski"},
            "Y": {"color": "#FFD93D", "name": "żółty"},
        },
        "grid": [
            "...RR...",
            "...BB...",
            "..BBBB..",
            "..BYYB..",
            "..BBBB..",
            ".RBBBBR.",
            ".RRBBRR.",
            "...YY...",
        ],
        "hints": [
            "Czubek rakiety jest czerwony, a okienko żółte.",
            "Skrzydła po bokach są czerwone – w szóstym i siódmym wierszu.",
            "Ogień z silnika to dwa żółte pola na samym dole.",
        ],
    },
    {
        "id": 6,
        "title": "🐠 Rybka",
        "description": "Pomarańczowa rybka puszcza bąbelki!",
        "size": 8,
        "palette": {
            "O": {"color": "#FF9F43", "name": "pomarańczowy"},
            "N": {"color": "#2F3542", "name": "czarny"},
            "B": {"color": "#54A0FF", "name": "niebieski"},
        },
        "grid": [
            "......B.",
            ".....B..",
            "...OOO..",
            "O.OOOOO.",
            "OOOOOON.",
            "O.OOOOO.",
            "...OOO..",
            "........",
        ],
        "hints": [
            "Bąbelki są niebieskie – na górze po prawej.",
            "Ogon rybki jest z lewej strony, a czarne oko z prawej.",
            "Środkowy wiersz rybki jest najdłuższy – aż 6 pomarańczowych pól i oko.",
        ],
    },
    {
        "id": 7,
        "title": "🍓 Truskawka",
        "description": "Słodka truskawka z pestkami.",
        "size": 8,
        "palette": {
            "R": {"color": "#FF4757", "name": "czerwony"},
            "G": {"color": "#2ED573", "name": "zielony"},
            "Y": {"color": "#FFD93D", "name": "żółty"},
        },
        "grid": [
            "...GG...",
            "..GGGG..",
            ".RRRRRR.",
            "RRYRRYRR",
            "RRRRRRRR",
            ".RYRRYR.",
            "..RRRR..",
            "...RR...",
        ],
        "hints": [
            "Listki na górze są zielone.",
            "Żółte pestki są w czwartym i szóstym wierszu.",
            "Truskawka zwęża się ku dołowi – jak trójkąt.",
        ],
    },
    {
        "id": 8,
        "title": "🤖 Robot",
        "description": "Zbuduj robota piksel po pikselu!",
        "size": 8,
        "palette": {
            "N": {"color": "#2F3542", "name": "czarny"},
            "B": {"color": "#54A0FF", "name": "niebieski"},
            "Y": {"color": "#FFD93D", "name": "żółty"},
            "R": {"color": "#FF4757", "name": "czerwony"},
        },
        "grid": [
            ".N....N.",
            "..N..N..",
            ".BBBBBB.",
            ".BYBBYB.",
            ".BBBBBB.",
            "..BRRB..",
            ".BBBBBB.",
            ".B.BB.B.",
        ],
        "hints": [
            "Robot ma dwie czarne antenki na górze.",
            "Oczy robota są żółte, a przyciski na brzuchu czerwone.",
            "Ostatni wiersz to nogi: niebieski, puste, dwa niebieskie, puste, niebieski.",
        ],
    },
    {
        "id": 9,
        "title": "🐝 Pszczółka",
        "description": "Bzz! Pszczółka w paski leci po miód.",
        "size": 8,
        "palette": {
            "Y": {"color": "#FFD93D", "name": "żółty"},
            "N": {"color": "#2F3542", "name": "czarny"},
            "W": {"color": "#F1F2F6", "name": "biały"},
        },
        "grid": [
            "........",
            ".W....W.",
            "..W..W..",
            "..YYYY..",
            ".YYNNYY.",
            ".YYYYYY.",
            ".YNNNNY.",
            "..YYYY..",
        ],
        "hints": [
            "Pierwszy wiersz jest cały pusty – nic nie malujesz!",
            "Białe skrzydełka są w drugim i trzecim wierszu.",
            "Pszczółka ma dwa czarne paski – jeden krótszy, drugi dłuższy.",
        ],
    },
    {
        "id": 10,
        "title": "🐧 Pingwin",
        "description": "Pingwinek z pomarańczowym dziobkiem.",
        "size": 8,
        "palette": {
            "N": {"color": "#2F3542", "name": "czarny"},
            "W": {"color": "#F1F2F6", "name": "biały"},
            "O": {"color": "#FF9F43", "name": "pomarańczowy"},
        },
        "grid": [
            "..NNNN..",
            ".NNNNNN.",
            ".NWNNWN.",
            ".NNOONN.",
            ".NWWWWN.",
            "NNWWWWNN",
            ".NWWWWN.",
            "..OO.OO.",
        ],
        "hints": [
            "Głowa pingwina jest czarna, a oczka białe.",
            "Dziobek to dwa pomarańczowe pola w czwartym wierszu.",
            "Na dole są łapki: 2 pomarańczowe, puste, 2 pomarańczowe.",
        ],
    },
    {
        "id": 11,
        "title": "🌈 Tęcza",
        "description": "Pięć kolorów tęczy – uważaj, żeby ich nie pomylić!",
        "size": 8,
        "palette": {
            "R": {"color": "#FF4757", "name": "czerwony"},
            "O": {"color": "#FF9F43", "name": "pomarańczowy"},
            "Y": {"color": "#FFD93D", "name": "żółty"},
            "G": {"color": "#2ED573", "name": "zielony"},
            "B": {"color": "#54A0FF", "name": "niebieski"},
        },
        "grid": [
            "..RRRR..",
            ".RROORR.",
            "ROOYYOOR",
            "OYYGGYYO",
            "YGGBBGGY",
            "GBB..BBG",
            "BB....BB",
            "........",
        ],
        "hints": [
            "Tęcza to łuki: najpierw czerwony, potem pomarańczowy, żółty, zielony i niebieski.",
            "Środek tęczy jest pusty – tam nic nie malujesz.",
            "Ostatni wiersz jest cały pusty!",
        ],
    },
    {
        "id": 12,
        "title": "🐱 Kotek",
        "description": "Rudy kotek z różowym noskiem.",
        "size": 8,
        "palette": {
            "O": {"color": "#FF9F43", "name": "pomarańczowy"},
            "N": {"color": "#2F3542", "name": "czarny"},
            "P": {"color": "#FD79A8", "name": "różowy"},
        },
        "grid": [
            ".O....O.",
            ".OO..OO.",
            ".OOOOOO.",
            "OONOONOO",
            "OOOOOOOO",
            "OOOPPOOO",
            ".OOOOOO.",
            "..O..O..",
        ],
        "hints": [
            "Uszy kotka rosną: najpierw 1 pole, potem 2 pola.",
            "Czarne oczka są w czwartym wierszu – trzecie i szóste pole.",
            "Różowy nosek to dwa pola w środku szóstego wiersza.",
        ],
    },
    {
        "id": 13,
        "title": "🍕 Pizza",
        "description": "Kawałek pizzy z pepperoni!",
        "size": 8,
        "palette": {
            "Y": {"color": "#FFD93D", "name": "żółty"},
            "R": {"color": "#FF4757", "name": "czerwony"},
            "K": {"color": "#FFE8C2", "name": "kremowy"},
        },
        "grid": [
            "...YY...",
            "..YYYY..",
            "..YRYY..",
            ".YYYYYY.",
            ".YRYYRY.",
            "YYYYYYYY",
            "YYYRYYYY",
            "KKKKKKKK",
        ],
        "hints": [
            "Kawałek pizzy jest coraz szerszy ku dołowi.",
            "Czerwone plasterki pepperoni są pojedynczymi polami.",
            "Ostatni wiersz to skórka – 8 kremowych pól z rzędu!",
        ],
    },
    {
        "id": 14,
        "title": "🎈 Balonik",
        "description": "Czerwony balonik na sznurku.",
        "size": 8,
        "palette": {
            "R": {"color": "#FF4757", "name": "czerwony"},
            "W": {"color": "#F1F2F6", "name": "biały"},
            "N": {"color": "#2F3542", "name": "czarny"},
        },
        "grid": [
            "..RRRR..",
            ".RWRRRR.",
            "RWRRRRRR",
            "RRRRRRRR",
            ".RRRRRR.",
            "..RRRR..",
            "...N....",
            "..N.....",
        ],
        "hints": [
            "Balonik jest okrągły – najpierw się rozszerza, potem zwęża.",
            "Białe pola to odblask światła – po lewej stronie balonika.",
            "Sznurek to jedno czarne pole w dwóch ostatnich wierszach.",
        ],
    },
    {
        "id": 15,
        "title": "🦋 Motylek",
        "description": "Motylek o dwukolorowych skrzydłach.",
        "size": 9,
        "palette": {
            "P": {"color": "#FD79A8", "name": "różowy"},
            "V": {"color": "#A55EEA", "name": "fioletowy"},
            "N": {"color": "#2F3542", "name": "czarny"},
        },
        "grid": [
            "PP.....PP",
            "PPP...PPP",
            "PPPPNPPPP",
            ".PPPNPPP.",
            "..VVNVV..",
            ".VVVNVVV.",
            "VVV.N.VVV",
            "VV..N..VV",
            "....N....",
        ],
        "hints": [
            "Czarna linia w środku to tułów motyla – jedno pole w każdym wierszu.",
            "Górne skrzydła są różowe, dolne fioletowe.",
            "Motyl jest symetryczny – prawa strona to lustro lewej!",
        ],
    },
    {
        "id": 16,
        "title": "🌳 Drzewko",
        "description": "Zielone drzewko z brązowym pniem.",
        "size": 9,
        "palette": {
            "G": {"color": "#2ED573", "name": "zielony"},
            "D": {"color": "#1E824C", "name": "ciemnozielony"},
            "W": {"color": "#A0522D", "name": "brązowy"},
        },
        "grid": [
            "....G....",
            "...GGG...",
            "..GGDGG..",
            ".GGGGGGG.",
            "..GGDGG..",
            ".GGGGGGG.",
            "GGGGDGGGG",
            "....W....",
            "...WWW...",
        ],
        "hints": [
            "Korona drzewa to trzy trójkąty – każdy trochę szerszy.",
            "Ciemnozielone pola są zawsze dokładnie na środku wiersza.",
            "Pień jest brązowy – w dwóch ostatnich wierszach.",
        ],
    },
    {
        "id": 17,
        "title": "👑 Korona",
        "description": "Złota korona z kolorowymi klejnotami.",
        "size": 9,
        "palette": {
            "Y": {"color": "#FFD93D", "name": "żółty"},
            "R": {"color": "#FF4757", "name": "czerwony"},
            "B": {"color": "#54A0FF", "name": "niebieski"},
        },
        "grid": [
            "Y.......Y",
            "Y...Y...Y",
            "YY.YYY.YY",
            "YYYYYYYYY",
            "YYYYYYYYY",
            "YRYYBYYRY",
            "YYYYYYYYY",
            "YYYYYYYYY",
            ".........",
        ],
        "hints": [
            "Korona ma trzy szpice – lewy, środkowy i prawy.",
            "Klejnoty są w szóstym wierszu: czerwony, niebieski, czerwony.",
            "Ostatni wiersz jest pusty – korona kończy się wyżej.",
        ],
    },
    {
        "id": 18,
        "title": "🚗 Autko",
        "description": "Czerwone auto na czarnych kołach.",
        "size": 9,
        "palette": {
            "R": {"color": "#FF4757", "name": "czerwony"},
            "B": {"color": "#54A0FF", "name": "niebieski"},
            "N": {"color": "#2F3542", "name": "czarny"},
        },
        "grid": [
            ".........",
            ".........",
            "..RRRRR..",
            ".RBBRBBR.",
            "RRRRRRRRR",
            "RRRRRRRRR",
            "RRRRRRRRR",
            ".NN.R.NN.",
            ".NN...NN.",
        ],
        "hints": [
            "Dwa pierwsze wiersze są całkiem puste.",
            "Niebieskie pola to szyby – po dwa z każdej strony.",
            "Koła są czarne: 2 pola z lewej i 2 z prawej.",
        ],
    },
    {
        "id": 19,
        "title": "🐼 Panda",
        "description": "Panda z czarnymi uszami – duża siatka 10×10!",
        "size": 10,
        "palette": {
            "N": {"color": "#2F3542", "name": "czarny"},
            "W": {"color": "#F1F2F6", "name": "biały"},
            "P": {"color": "#FD79A8", "name": "różowy"},
        },
        "grid": [
            "NN......NN",
            "NNN....NNN",
            ".WWWWWWWW.",
            "WWWWWWWWWW",
            "WWNWWWWNWW",
            "WWNWWWWNWW",
            "WWWWNNWWWW",
            "WPWWNNWWPW",
            ".WWWWWWWW.",
            "..WWWWWW..",
        ],
        "hints": [
            "Czarne uszy są w dwóch pierwszych wierszach, po bokach.",
            "Oczka pandy to pojedyncze czarne pola w piątym i szóstym wierszu.",
            "Różowe policzki są na samych brzegach ósmego wiersza.",
        ],
    },
    {
        "id": 20,
        "title": "🏰 Zamek",
        "description": "Zamek z wieżami i flagami – najtrudniejszy obrazek!",
        "size": 10,
        "palette": {
            "S": {"color": "#A4B0BE", "name": "szary"},
            "R": {"color": "#FF4757", "name": "czerwony"},
            "N": {"color": "#2F3542", "name": "czarny"},
        },
        "grid": [
            ".R......R.",
            "SSS.SS.SSS",
            "SSSSSSSSSS",
            "SNSSSSSSNS",
            "SSSSSSSSSS",
            "SSSSNNSSSS",
            "SSSNNNNSSS",
            "SSSNNNNSSS",
            "SSSNNNNSSS",
            "SSSSSSSSSS",
        ],
        "hints": [
            "Na górze są dwie czerwone flagi – każda to jedno pole.",
            "Blanki zamku mają przerwy: 3 szare, puste, 2 szare, puste, 3 szare.",
            "Czarne pola w środku to brama, a dwa pojedyncze – okienka wież.",
        ],
    },
]
