"""KidCoder – 10 programming quiz questions."""

QUIZ_QUESTIONS = [
    {
        "id": 1,
        "title": "Co to jest zmienna?",
        "description": "Podstawy programowania",
        "question": "Zmienna w programowaniu to jak...",
        "options": ["Pudełko na dane", "Rodzaj pętli", "Typ robota", "Nazwa komputera"],
        "correct": 0,
        "explanation": "Zmienna to jak pudełko z etykietą, w którym przechowujemy dane (liczby, tekst itp.).",
        "hints": ["Pomyśl o szufladzie z opisem, do której wkładasz coś"],
    },
    {
        "id": 2,
        "title": "Co robi pętla?",
        "description": "Sterowanie programem",
        "question": "Pętla w programowaniu służy do...",
        "options": ["Powtarzania czynności", "Rysowania kółek", "Wyłączania komputera", "Pisania listów"],
        "correct": 0,
        "explanation": "Pętla powtarza blok kodu określoną liczbę razy lub dopóki warunek jest prawdziwy.",
        "hints": ["Wyobraź sobie, że mówisz: powtórz to 5 razy"],
    },
    {
        "id": 3,
        "title": "Jaki wynik?",
        "description": "Śledzenie kodu",
        "question": "Co wypisze ten kod?",
        "code": "x = 3\nx = x + 2\nprint(x)",
        "options": ["5", "3", "2", "32"],
        "correct": 0,
        "explanation": "x zaczyna jako 3, potem dodajemy 2, więc x = 5.",
        "hints": ["Policz: 3 + 2 = ?"],
    },
    {
        "id": 4,
        "title": "Warunek IF",
        "description": "Instrukcje warunkowe",
        "question": "Co się stanie?",
        "code": "wiek = 10\nif wiek >= 7:\n    print('Szkoła!')\nelse:\n    print('Przedszkole!')",
        "options": ["Wypisze: Szkoła!", "Wypisze: Przedszkole!", "Nic nie wypisze", "Błąd"],
        "correct": 0,
        "explanation": "10 jest większe od 7, więc warunek jest prawdziwy i wypisuje 'Szkoła!'.",
        "hints": ["Czy 10 >= 7? Tak czy nie?"],
    },
    {
        "id": 5,
        "title": "Typ danych",
        "description": "Rodzaje danych",
        "question": "Które z poniższych to tekst (string)?",
        "options": ['"Cześć"', "42", "True", "3.14"],
        "correct": 0,
        "explanation": "Tekst (string) zapisujemy w cudzysłowie. Liczby i True/False to inne typy.",
        "hints": ["Szukaj cudzysłowu"],
    },
    {
        "id": 6,
        "title": "Funkcja",
        "description": "Definiowanie funkcji",
        "question": "Co robi słowo 'return' w funkcji?",
        "code": "def dodaj(a, b):\n    return a + b\n\nwynik = dodaj(3, 4)",
        "options": ["Zwraca wynik", "Kończy program", "Drukuje tekst", "Tworzy zmienną"],
        "correct": 0,
        "explanation": "return zwraca wartość z funkcji – tutaj dodaj(3,4) zwraca 7.",
        "hints": ["return = zwróć coś z powrotem"],
    },
    {
        "id": 7,
        "title": "Lista",
        "description": "Kolekcje danych",
        "question": "Ile elementów ma ta lista?",
        "code": 'owoce = ["jabłko", "banan", "kiwi"]',
        "options": ["3", "1", "2", "4"],
        "correct": 0,
        "explanation": "Lista ma 3 elementy oddzielone przecinkami: jabłko, banan, kiwi.",
        "hints": ["Policz elementy między nawiasami kwadratowymi"],
    },
    {
        "id": 8,
        "title": "Znajdź błąd",
        "description": "Debugowanie kodu",
        "question": "Który wiersz ma błąd?",
        "code": 'imie = "Ala"\nprint("Cześć " + imie\nprint("Jak się masz?")',
        "options": ["Wiersz 2 – brak nawiasu )", "Wiersz 1", "Wiersz 3", "Nie ma błędu"],
        "correct": 0,
        "explanation": "W wierszu 2 brakuje zamykającego nawiasu ')' na końcu.",
        "hints": ["Sprawdź nawiasy – każdy ( musi mieć swoje )"],
    },
    {
        "id": 9,
        "title": "Pętla FOR",
        "description": "Iteracja",
        "question": "Ile razy wypisze 'Hej'?",
        "code": 'for i in range(4):\n    print("Hej")',
        "options": ["4 razy", "3 razy", "5 razy", "1 raz"],
        "correct": 0,
        "explanation": "range(4) daje: 0, 1, 2, 3 – czyli 4 powtórzenia.",
        "hints": ["range(4) zaczyna od 0 i kończy przed 4"],
    },
    {
        "id": 10,
        "title": "Prawda czy fałsz?",
        "description": "Wartości logiczne",
        "question": "Jaką wartość ma wyrażenie: 5 > 3 and 2 < 1?",
        "options": ["False", "True", "5", "Błąd"],
        "correct": 0,
        "explanation": "5 > 3 to True, ale 2 < 1 to False. True AND False = False.",
        "hints": ["AND wymaga, żeby OBA warunki były prawdziwe"],
    },
]
