"""KidCoder – Computational Thinking exercises for young learners."""

THINKING_EXERCISES = [
    # --- SEQUENCING ---
    {
        "id": 1,
        "title": "📋 Kolejność: Śniadanie",
        "description": "Ułóż czynności w prawidłowej kolejności!",
        "type": "sequence_order",
        "instruction": "Jak przygotować śniadanie? Ułóż kroki od 1 do 4:",
        "items": ["🥣 Zjedz płatki", "🥛 Nalej mleko", "🥣 Wsyp płatki do miski", "🍽️ Weź miskę"],
        "correct_order": [3, 2, 1, 0],
        "explanation": "Sekwencja to kroki wykonywane po kolei — jak przepis! Komputer też wykonuje instrukcje jedna po drugiej.",
        "hints": ["Co robisz najpierw — jesz czy bierzesz miskę?"],
    },
    {
        "id": 2,
        "title": "📋 Kolejność: Budowanie wieży",
        "description": "Ułóż klocki od dołu do góry!",
        "type": "sequence_order",
        "instruction": "Jak zbudować wieżę z klocków? Ułóż kroki:",
        "items": ["🔴 Połóż mały klocek na górze", "🟢 Połóż średni klocek", "🔵 Połóż duży klocek na dole", "⭐ Połóż gwiazdkę na szczycie"],
        "correct_order": [2, 1, 0, 3],
        "explanation": "Programy działają jak budowanie wieży — każdy krok musi być we właściwej kolejności!",
        "hints": ["Największy klocek idzie na dół"],
    },
    # --- CONDITIONS ---
    {
        "id": 3,
        "title": "🚦 Warunek: Semafor",
        "description": "Co zrobisz gdy zobaczysz dany kolor?",
        "type": "condition",
        "instruction": "Patrzysz na semafor. Jakie jest prawidłowe zachowanie?",
        "scenario": "🚦 Światło jest CZERWONE",
        "options": ["🚶 Idź!", "🛑 Stój i czekaj!", "🏃 Biegnij szybko!"],
        "answer": 1,
        "explanation": "JEŻELI światło = czerwone TO stój. To jest warunek (IF) — komputer sprawdza i wybiera co zrobić!",
        "hints": ["Czerwone światło oznacza STOP"],
    },
    {
        "id": 4,
        "title": "🌧️ Warunek: Pogoda",
        "description": "Co założyć na siebie?",
        "type": "condition",
        "instruction": "Wychodzisz z domu. Na dworze pada deszcz ☔. Co zabierasz?",
        "scenario": "🌧️ Na dworze PADA DESZCZ",
        "options": ["🕶️ Okulary przeciwsłoneczne", "☂️ Parasol", "🩳 Krótkie spodenki"],
        "answer": 1,
        "explanation": "JEŻELI pada deszcz TO weź parasol. Komputer też podejmuje decyzje na podstawie warunków!",
        "hints": ["Co chroni przed deszczem?"],
    },
    # --- PATTERNS ---
    {
        "id": 5,
        "title": "🔮 Wzorzec: Kolorowy szlak",
        "description": "Znajdź następny element we wzorcu!",
        "type": "pattern",
        "instruction": "Jaki element jest następny w sekwencji?",
        "sequence": ["🔴", "🔵", "🔴", "🔵", "🔴", "?"],
        "options": ["🔴", "🔵", "🟢", "🟡"],
        "answer": 1,
        "explanation": "Wzorzec to coś co się powtarza! 🔴🔵🔴🔵... Komputery szukają wzorców w danych — tak samo jak Ty!",
        "hints": ["Patrz na kolory po kolei — co się powtarza?"],
    },
    {
        "id": 6,
        "title": "🔮 Wzorzec: Kształty",
        "description": "Kontynuuj sekwencję kształtów!",
        "type": "pattern",
        "instruction": "Jaki kształt jest następny?",
        "sequence": ["⭐", "🔵", "⭐", "🔵", "⭐", "?"],
        "options": ["⭐", "🔵", "🔴", "🟡"],
        "answer": 1,
        "explanation": "Wzorce w programowaniu nazywamy pętlami — coś powtarza się w kółko!",
        "hints": ["Gwiazdka, kółko, gwiazdka, kółko..."],
    },
    # --- LOOPS ---
    {
        "id": 7,
        "title": "🔄 Pętla: Rysowanie",
        "description": "Co narysuje ta pętla?",
        "type": "loop_result",
        "instruction": "Robot rysuje kształty. POWTÓRZ 3 RAZY: narysuj ⭐. Co powstanie?",
        "loop_code": "POWTÓRZ 3 RAZY:\n  narysuj ⭐",
        "options": ["⭐", "⭐⭐", "⭐⭐⭐", "⭐⭐⭐⭐"],
        "answer": 2,
        "explanation": "Pętla 'POWTÓRZ 3 RAZY' wykonuje akcję dokładnie 3 razy. Zamiast pisać to samo 3 razy, mówimy: powtórz!",
        "hints": ["Policz: raz, dwa, trzy — ile gwiazdek?"],
    },
    {
        "id": 8,
        "title": "🔄 Pętla: Zbieranie jabłek",
        "description": "Ile jabłek zbierze robot?",
        "type": "loop_result",
        "instruction": "Robot zbiera jabłka. POWTÓRZ 4 RAZY: weź 🍎. Ile jabłek ma robot?",
        "loop_code": "POWTÓRZ 4 RAZY:\n  weź 🍎",
        "options": ["2 jabłka", "3 jabłka", "4 jabłka", "5 jabłek"],
        "answer": 2,
        "explanation": "Robot powtarza zbieranie 4 razy = 4 jabłka! Pętla to sposób na wielokrotne wykonanie tego samego.",
        "hints": ["POWTÓRZ 4 RAZY oznacza... 4 razy!"],
    },
    # --- DEBUGGING ---
    {
        "id": 9,
        "title": "🐛 Debugowanie: Błąd robota",
        "description": "Znajdź błąd w programie robota!",
        "type": "debugging",
        "instruction": "Robot ma dojść do 🏠 domu. Idzie: ➡️ ➡️ ⬆️ ➡️. Ale utknął! Który krok jest zły?",
        "visual": [
            ["⬜", "⬜", "⬜", "🏠"],
            ["⬜", "⬜", "⬛", "⬜"],
            ["🤖", "⬜", "⬜", "⬜"],
        ],
        "steps": ["➡️ W prawo", "➡️ W prawo", "⬆️ W górę", "➡️ W prawo"],
        "wrong_step": 1,
        "correct_step": "⬆️ W górę",
        "explanation": "Debugowanie to szukanie błędów! Dobra trasa: ➡️ ⬆️ ⬆️ ➡️. Programiści szukają bugów w kodzie tak samo!",
        "hints": ["Narysuj trasę palcem — gdzie robot uderza w ścianę?"],
    },
    {
        "id": 10,
        "title": "🐛 Debugowanie: Kanapka",
        "description": "Znajdź błąd w przepisie!",
        "type": "debugging",
        "instruction": "Przepis na kanapkę: 1) Weź chleb 2) Połóż ser 3) Zamknij kanapkę 4) Pokrój chleb. Co jest nie tak?",
        "steps": ["🍞 Weź chleb", "🧀 Połóż ser", "🥪 Zamknij kanapkę", "🔪 Pokrój chleb"],
        "wrong_step": 3,
        "correct_step": "Pokrój chleb PRZED zamknięciem!",
        "explanation": "Krok 'pokrój chleb' powinien być PRZED zamknięciem kanapki! Kolejność instrukcji jest bardzo ważna w programowaniu.",
        "hints": ["Czy możesz pokroić chleb po zamknięciu kanapki?"],
    },
    # --- DECOMPOSITION ---
    {
        "id": 11,
        "title": "🧩 Rozkładanie: Sprzątanie pokoju",
        "description": "Podziel duże zadanie na małe kroki!",
        "type": "decomposition",
        "instruction": "Mama mówi: 'Posprzątaj pokój!' To duże zadanie. Które kroki do niego należą?",
        "task": "🧹 Posprzątaj pokój!",
        "options": [
            {"text": "📦 Schowaj zabawki", "correct": True},
            {"text": "🛏️ Pościel łóżko", "correct": True},
            {"text": "🍕 Zamów pizzę", "correct": False},
            {"text": "🧹 Zamieć podłogę", "correct": True},
            {"text": "🎮 Pograj w grę", "correct": False},
        ],
        "explanation": "Dekompozycja = podzielenie dużego problemu na małe kroki. Programiści robią to ze złożonymi zadaniami!",
        "hints": ["Które czynności pomagają w sprzątaniu?"],
    },
    {
        "id": 12,
        "title": "🧩 Rozkładanie: Rysowanie robota",
        "description": "Z jakich kształtów składa się robot?",
        "type": "decomposition",
        "instruction": "Chcesz narysować robota 🤖. Wybierz elementy, które potrzebujesz:",
        "task": "🤖 Narysuj robota!",
        "options": [
            {"text": "⬜ Kwadratowa głowa", "correct": True},
            {"text": "⬜ Prostokątne ciało", "correct": True},
            {"text": "🌳 Drzewo", "correct": False},
            {"text": "⭕ Koła na ręce", "correct": True},
            {"text": "🐱 Kocie uszy", "correct": False},
        ],
        "explanation": "Robot składa się z prostych kształtów! Tak samo programy składają się z prostych instrukcji.",
        "hints": ["Czy robot ma kocie uszy? 😄"],
    },
    # --- ALGORITHMS ---
    {
        "id": 13,
        "title": "🗺️ Algorytm: Droga do szkoły",
        "description": "Wybierz najlepszą drogę!",
        "type": "algorithm",
        "instruction": "Musisz dojść z 🏠 domu do 🏫 szkoły. Która droga jest najkrótsza?",
        "visual": [
            ["🏠", "➡️", "⬜", "⬛", "⬜"],
            ["⬜", "⬜", "⬜", "⬛", "⬜"],
            ["⬛", "⬛", "⬜", "⬜", "⬜"],
            ["⬜", "⬜", "⬜", "⬛", "🏫"],
        ],
        "options": [
            "➡️➡️⬇️⬇️➡️➡️⬇️⬇️",
            "⬇️⬇️➡️➡️➡️⬇️➡️",
            "➡️➡️⬇️⬇️➡️⬇️➡️",
        ],
        "answer": 2,
        "explanation": "Algorytm to plan krok po kroku. Wybieramy najlepszą drogę — tak jak GPS szuka najkrótszej trasy!",
        "hints": ["Policz kroki w każdej drodze"],
    },
    {
        "id": 14,
        "title": "🗺️ Algorytm: Sortowanie",
        "description": "Posortuj liczby od najmniejszej!",
        "type": "algorithm",
        "instruction": "Ułóż liczby od najmniejszej do największej: 5, 2, 8, 1",
        "options": ["1, 2, 5, 8", "2, 1, 5, 8", "8, 5, 2, 1", "1, 5, 2, 8"],
        "answer": 0,
        "explanation": "Sortowanie to jeden z najważniejszych algorytmów! Komputery sortują miliony rzeczy w sekundę.",
        "hints": ["Znajdź najmnijeszą liczbę — to pierwszy element"],
    },
    # --- ABSTRACTION ---
    {
        "id": 15,
        "title": "🎭 Abstrakcja: Co jest ważne?",
        "description": "Wybierz najważniejsze informacje!",
        "type": "abstraction",
        "instruction": "Piszesz listę zakupów. Co Jest WAŻNE na liście?",
        "task": "📝 Lista zakupów",
        "options": [
            {"text": "🥛 Mleko", "correct": True},
            {"text": "🌤️ Jaka jest pogoda", "correct": False},
            {"text": "🍎 Jabłka", "correct": True},
            {"text": "🎵 Ulubiona piosenka", "correct": False},
            {"text": "🍞 Chleb", "correct": True},
        ],
        "explanation": "Abstrakcja = skupienie się na tym, co WAŻNE i ignorowanie reszty. Programiści pomijają nieistotne szczegóły!",
        "hints": ["Czy pogoda pomoże ci kupić jedzenie?"],
    },
    {
        "id": 16,
        "title": "🎭 Abstrakcja: Opis zwierzaka",
        "description": "Co jest najważniejsze żeby rozpoznać kota?",
        "type": "abstraction",
        "instruction": "Jak opisać KOTA komputerowi? Wybierz najważniejsze cechy:",
        "task": "🐱 Opisz kota",
        "options": [
            {"text": "🐾 Ma 4 łapy", "correct": True},
            {"text": "😺 Mówi 'miau'", "correct": True},
            {"text": "📅 Jest wtorek", "correct": False},
            {"text": "🐈 Ma ogon i wąsy", "correct": True},
            {"text": "🌍 Ziemia jest okrągła", "correct": False},
        ],
        "explanation": "Abstrakcja w programowaniu to opisanie obiektu przez jego NAJWAŻNIEJSZE cechy. Kot = 4 łapy + miau + wąsy!",
        "hints": ["Które fakty opisują KOTA, a które nie?"],
    },
]
