"""KidCoder – 6 typing lessons."""

TYPING_LESSONS = [
    {
        "id": 1,
        "title": "Litery domowe",
        "description": "Poznaj klawisze środkowego rzędu: A S D F G H J K L",
        "type": "letters",
        "chars": "asdfghjkl",
        "words": ["ala", "las", "sad", "dal", "hak", "jak", "gal", "lag"],
        "time_limit": 120,
        "min_wpm": 5,
    },
    {
        "id": 2,
        "title": "Górny rząd",
        "description": "Ćwicz klawisze górnego rzędu: Q W E R T Y U I O P",
        "type": "letters",
        "chars": "qwertyuiop",
        "words": ["wir", "top", "por", "tur", "rów", "wet", "typ", "ryp"],
        "time_limit": 120,
        "min_wpm": 5,
    },
    {
        "id": 3,
        "title": "Dolny rząd",
        "description": "Ćwicz klawisze dolnego rzędu: Z X C V B N M",
        "type": "letters",
        "chars": "zxcvbnm",
        "words": ["raz", "ban", "van", "max", "noc", "bez", "bam"],
        "time_limit": 120,
        "min_wpm": 5,
    },
    {
        "id": 4,
        "title": "Proste słowa",
        "description": "Pisz całe słowa! Szybko i dokładnie!",
        "type": "words",
        "words": ["kot", "dom", "las", "oko", "nos", "rak", "sok", "lis", "mak",
                   "pies", "ryba", "lato", "zima", "mama", "tata", "drzewo", "morze"],
        "time_limit": 180,
        "min_wpm": 8,
    },
    {
        "id": 5,
        "title": "Komendy kodu",
        "description": "Pisz prawdziwe komendy programistyczne!",
        "type": "code",
        "words": ["print", "for i in", "if x >", "while", "def fun", "return",
                   "list", "True", "False", "import", "class", "self", "None"],
        "time_limit": 180,
        "min_wpm": 10,
    },
    {
        "id": 6,
        "title": "Zdania",
        "description": "Pisz całe zdania – jak prawdziwy programista!",
        "type": "sentences",
        "words": [
            "Ala ma kota",
            "kot siedzi na macie",
            "program działa dobrze",
            "pętla się powtarza",
            "funkcja zwraca wynik",
            "robot idzie do przodu",
        ],
        "time_limit": 240,
        "min_wpm": 12,
    },
]
